### ISSUE TITLE
onMoveItem() crash?

### ISSUE THREAD

**Issue by mazurio** [h6ah4i/android-advancedrecyclerview#10]
Hi, 
We got this crash report couple of times in last few weeks since we moved to Advanced Recycler View.

https://gist.github.com/mazurio/ce9b2b3cc4d95a7c710b

We are currently using stable ids and also each id is unique by random number so it shouldn't crash, the crash happened when there were two items and I started dragging it back and forth.

Any ideas? I haven't updated the library yet to the newest one, 0.6.0 is currently used.

Damian

**Comment by mazurio** [comment]
Upgraded to 0.6.2 to see if anything has changed.

**Comment by h6ah4i** [comment]
Hi Damian,
Thank you for your report. I'll try to reproduce and fix this issue, so I want ask you more detail of the situation.

1. Do you use any other Advanced RecyclerView features (swipe, expand) or other third party libraries? 
2. What is the version of  Android OS?

Thanks

**Comment by mazurio** [comment]
Hello,

For the advanced recycler view features we use swiping and dragging, no other third party libraries in the same codebase but we use another listener for clicking. I cannot reproduce it often because it happens on different platforms (4.0 and 5.0), so far it happened twice.

I will also message you on Monday with the project that is using Advanced Recycler View to update the GitHub page.

Thanks,
Damian

**Comment by h6ah4i** [comment]
Hi Damian,
Any update on this issue?

**Comment by mazurio** [comment]
I think so far, there was no crashes but I have also moved to different project so can't update for now until it's released. I will update if I know anything more, I think it's safe to close for now?

**Comment by h6ah4i** [comment]
Thanks for your response. Okay, I think it should be better to close this issue for now and please re-open this issue if needed.

Could you close this issue yourself in order to keep re-opeanable?

ref.) http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github
> * you can re-open your own issues *if you closed them yourself
