### ISSUE TITLE
Implementing with lists of classes

### ISSUE THREAD

**Issue by DJSavage** [h6ah4i/android-advancedrecyclerview#101]
This is definitely the best featured library for an expandable recyclerview available from all the ones I've looked into. But the lack of proper documentation has meant that I haven't been able to trial it in my app.

I want to send the data to the adapter in this format:
[List of Parent]
    String *something*
    String *something*
    [List of Child]
        *various data*
    [end Child]
[end Parent]

But I'm finding myself chasing the code round and round in circles to find where I can send the data like this and what bits of code I need or need to alter. The code suggestions for the expandable recyclerview just don't seem to point to enough of the code to make an informed decision.

Please advise, or provide some documentation if possible.

**Comment by Shvet** [comment]
I need to implement same way as you want. if you have found solution, please post here.

**Comment by h6ah4i** [comment]
Hi.

> I want to send the data to the adapter in this format:
> [List of Parent]
>   String something
>   String something
>   [List of Child]
>     various data
>   [end Child]
> [end Parent]

That seems nothing special. Implement like the following; (however I haven't tested yet)

```java
// creating a data set
List<Object> parentList = new ArrayList<>();
List<String> childList = new ArrayList<>();
parentList.add("Group item 1");
parentList.add("Group item 2");
childList.add("Child item 1");
childList.add("Child item 2");
parentList.add(childItem);
```

```java
// part of the adapter implementation

int getGroupCount() {
   return parentList.size();
}

int getChildCount(int groupPosition) {
    Object item = parentList.get(groupPosition);
    if (item instanceOf List<?>) {
       // group item
       return ((List<Object>) item).size();
   } else {
        // child item
        return 0;
   }
}

long getGroupId(int groupPosition) {
    // NOTE: If you want to update the contents of the list, need to provide a *stable* ID instead of just returning the item position.
    return groupPosition;
}

long getChildId(int groupPosition, int childPosition) {
    // NOTE: If you want to update the contents of the list, need to provide a *stable* ID instead of just returning the item position.
    return childPosition;
}

int getGroupItemViewType(int groupPosition) {
    return 0;
}

int getChildItemViewType(int groupPosition, int childPosition) {
    return 0;
}

GVH onCreateGroupViewHolder(ViewGroup parent, int viewType) {
    return new GVH(LayoutInflater.from(parent.getContext()).inflate(..., parent, false));
}

CVH onCreateChildViewHolder(ViewGroup parent, int viewType) {
    return new CVH(LayoutInflater.from(parent.getContext()).inflate(..., parent, false));
}

void onBindGroupViewHolder(GVH holder, int groupPosition, int viewType) {
    Object item = parentList.get(groupPosition);
    // bind the group view
}

void onBindChildViewHolder(CVH holder, int groupPosition, int childPosition, int viewType) {
    String item = ((List<String>) parentList.get(groupPosition)).get(childPosition);
    // bind the child view
}
```

--- 

> The code suggestions for the expandable recyclerview just don't seem to point to enough of the code to make an informed decision.

This is a limitation of current Gradle and Android Studio. This library is provided as the AAR format, so the source jar file will not downloaded automatically.  I have updated the README and added a workaround for this problem. Try the following Gradle script;

```groovy
buildscript {
    repositories {
        maven { url 'https://raw.github.com/xujiaao/mvn-repository/master/releases' }
    }

    dependencies {
        classpath 'com.github.xujiaao:aarLinkSources:1.0.0'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'aar-link-sources'

android {
    ...
}

dependencies {
    compile ('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.7.4@aar'){
        transitive=true
    }
    aarLinkSources 'com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.7.4:sources@jar'
}
```

**Comment by Shvet** [comment]
I tried your solution but it is not calling any methods of adapter like **onCreateGroupViewHolder**, **onCreateChildViewHolder**, **onBindGroupViewHolder**,....

can you tell me why it is like that?

**Comment by Shvet** [comment]
Thanks. It worked.
