### ISSUE TITLE
java.lang.IllegalStateException: already have a wrapped adapter

### ISSUE THREAD

**Issue by Shvet** [h6ah4i/android-advancedrecyclerview#104]
When i repopulate recyclerview with new data it is giving me java.lang.IllegalStateException: already have a wrapped adapter error. I tried to check library code and found that if i have already set adapter in **`RecyclerViewExpandableItemManager`** it will through **`IllegalArgumentException`** error. 

Actually i am trying to show data from webservice which will be refreshed after every few time so now if i have already populated data once it will not going to show new data.

can you suggest any solution?

**Comment by h6ah4i** [comment]
Hi. That is an intended behavior of this library. If you want to refresh the all of the list items, I can suggest two approaches.

### Approach 1
Implement a `setData()` or some sort of method to the adapter, and then call the [`notifyDataSetChanged()`](https://developer.android.com/intl/ja/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyDataSetChanged()) method.

### Approach 2
Recreate everything. Dispose adapters and `RecyclerViewExpandableItemManager`, then create a new adapter, new wrapped adapter, and a new `RecyclerViewExpandableItemManager` instance.



### Related issue
- [Issue #77 - Changing the data for the expandable recycler view throws ClassCastException on item click](https://github.com/h6ah4i/android-advancedrecyclerview/issues/77)

**Comment by Shvet** [comment]
Solved the problem. I am editing library according to my requirement too. 


Thanks/Regards
