### ISSUE TITLE
Hi sir, im newbie! I have one question for your lib about spilit only swipe

### ISSUE THREAD

**Issue by mrkentlng** [h6ah4i/android-advancedrecyclerview#106]
Im try clone in desktop then i got full your project and run it succesfull on my device! But now im want export only recycleview with swipe! How can i do that? 
Im try compile to new project! But when i try implement! Something got wrong! Please help me fix this! Export only recycleview with swipe! My english very bad, im newbie dev android! So please help me! Thanks you so much!

**Comment by h6ah4i** [comment]
Hi. Sorry, I'm not sure what exactly you want to achieve.

Do you want to make a **minimal example app which only supports swiping**? OR... Do you want to **modify the library to remove all features except for swiping*?
