### ISSUE TITLE
Force expand/colapse

### ISSUE THREAD

**Issue by jkwiecien** [h6ah4i/android-advancedrecyclerview#11]
I wish I could expand/collapse group programatically without allowing user to do that. Is that possible in current implementation?

I think it would be possible if you make ExpandableRecyclerViewWrapperAdapter public :)

**Comment by h6ah4i** [comment]
Hi @jkwiecien,

Yes, that is possible to implement in current implementation. Please use these methods;

- `RecyclerViewExpandableItemManager.expandGroup(int groupPosition)`
- `RecyclerViewExpandableItemManager.collapseGroup(int groupPosition)`

FYI: If you don't want to expand/collapse a group when touching the item, please implement the `onCheckCanExpandOrCollapseGroup()` method always returns false.

**Comment by jkwiecien** [comment]
Thanks! :)
