### ISSUE TITLE
Drag is not working when a drag handle is small

### ISSUE THREAD

**Issue by JinSB** [h6ah4i/android-advancedrecyclerview#111]
My drag handle is little small (56dp x 56dp). I just tested with small touch pen. There two error cases.
1. Click top & drag upper direction. ( drag canceled )
2. Click bottom & Drag downward direction. ( drag canceled )

Below two cases are working fine.
1. Click top & drag downward direction. ( drag success )
2. Click bottom & Drag upper direction. ( drag success )

I'm checking ViewUtils.hitTest but can not understand. 

Thank you very much for Advancedrecyclerview.

**Comment by h6ah4i** [comment]
Thanks, I'll fix this in next release.

**Comment by h6ah4i** [comment]
0.8.0 is out.
