### ISSUE TITLE
GroupPosition and ChildPosition at ChildView Click Listener 

### ISSUE THREAD

**Issue by Shvet** [h6ah4i/android-advancedrecyclerview#113]
I want to know is there anyway to get groupPosition at childview click listener?

I have get childPosition by using mRecyclerView.getChildAdapterPosition(v); in public void onItemViewClicked(View v, boolean pinned) which is defined in interface.

Also There is one more Question. Can i show original view after swipe? I dont want to show any color after swipe is done. Like if i swipe a view only 15% it will go back to original position i want to do same for full swipe.

Thanks/Regards

**Comment by h6ah4i** [comment]
Hi :)

> I have get childPosition by using mRecyclerView.getChildAdapterPosition(v); in public void onItemViewClicked(View v, boolean pinned) which is defined in interface.

```
// Almost same as the ExpandableListAdapter class in Android framework.
// adapter position (flat position) -> expandablePosition (packed position) -> group & child position

int flatPosition = mRecyclerView.getChildAdapterPosition(v);
long expandablePosition = mExpandableItemManager.getExpandablePosition(flatPosition);
int groupPosition = RecyclerViewExpandableItemManager.getPackedPositionGroup(expandablePosition);
int childPosition = RecyclerViewExpandableItemManager.getPackedPositionChild(expandablePosition);
```

> Can i show original view after swipe? I dont want to show any color after swipe is done. Like if i swipe a view only 15% it will go back to original position i want to do same for full swipe.

Do not set the background resource in the `onBindViewHolder()` and the `onSetSwipeBackground()` methods.

**Comment by Shvet** [comment]
Thanks  Both Solution Worked for me.
