### ISSUE TITLE
can i build a  horizontal recyclerview？

### ISSUE THREAD

**Issue by lushan1314** [h6ah4i/android-advancedrecyclerview#116]
can i build a  horizontal recyclerview  with this ？ i need a horizontal recyclerview and  it can drag items。
how can i do this？
thank you

**Comment by h6ah4i** [comment]
Currently that is available in the develop branch code only. It will be included in next release (v0.8.0).

**Comment by h6ah4i** [comment]
0.8.0 is out.

**Comment by lushan1314** [comment]
great！thank you very much

**Comment by softmarshmallow** [comment]
within
`        recyclerView.setLayoutManager(new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false));
`

RecyclerView wont Change Horizontal...
using the same sample code, just replacing the setLayoutManager line.

solutions?
