### ISSUE TITLE
Reverse Animation

### ISSUE THREAD

**Issue by pixelbendr** [h6ah4i/android-advancedrecyclerview#120]
Hello I noticed in the swipe example when you click "cancel" on the dialog the animation reverses the unpin but I tried it and it doesn't work for me in my project. What am doing is setting item.setPin(false) and notifyItemChanged(position) but no animation. :( need help

**Comment by h6ah4i** [comment]
Hi. Maybe, you havw to call the `setSwipeItemHorizontalSlideAmount()` in the `onBindItemView()`. Please check the following implementation. 

https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.8.0/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_s/MySwipeableItemAdapter.java#L155

Thanks.

**Comment by pixelbendr** [comment]
When I call setSwipeItemHorizontalSlideAmount() I get some very unusual animation and items appearing at random positions but I will try it again. Thanks for this.

**Comment by pixelbendr** [comment]
Not working. Also noticed onItemPinned is not called sometimes when I swipe to the end of the screen so the view get stacked in pin mode. :(

**Comment by h6ah4i** [comment]
OK. I have more advices. Do you implement your adapter class provides stable ID for each items? This library requires stable ID to work properly. Then, do you disable "item change animations" by calling the `setSupportsChangeAnimations()` method?

**Comment by pixelbendr** [comment]
Yes Please, am doing both, still same issues. Looked at the example, am doing everything to get swiping to work but I have disabled click events etc. because I don't need them?

**Comment by h6ah4i** [comment]
Hmm... it's difficult to give more advices without taking a look an actual code. Could you show me your code, please?

**Comment by h6ah4i** [comment]
Close this issue due to long time of inactivity.
