### ISSUE TITLE
Long press should cancel when recycler view scrolls

### ISSUE THREAD

**Issue by grennis** [h6ah4i/android-advancedrecyclerview#124]
When long press detection is enabled and user touches a list item just to scroll the recyclerview, the touched item suddenly switches into drag mode unexpectedly. 

This is happening because the long press detector thinks user is long pressing an item but really they are just trying to scroll the recycler view. When the recycler view scrolls, the long touch detection should cancel.

**Comment by grennis** [comment]
Weird, this only happens on the simulator. On a real device, it's working fine. I'm closing this out

**Comment by grennis** [comment]
On a real device just scroll a recycler view slowly with finger and you can see the problem. Is there a workaround for this? Seems like I must be doing something wrong.

**Comment by vinayak-garg** [comment]
Funny, I added a pull request to fix this issue only - https://github.com/h6ah4i/android-advancedrecyclerview/pull/123

Can you try if it solves the issue for you? I know it worked for me.

**Comment by grennis** [comment]
After running through the samples I just wanted to point out that the demo doesn't show this problem because it defines a small area inside the recycler view item (a drag handle area) where user must click and hold or drag to re-order the items. But it's quite common, I think, to allow dragging from anywhere in the item to drag it. And you can reproduce the problem even with the demo by trying to scroll the recycler starting your finger in the drag handle area.

So thanks for your pull request, that does help. I think however, it appears you can still easily accidentally enter the drag mode even at 750ms. I think the ideal solution would be to allow the app to either programmatically enter drag mode based on it's own criteria - i.e., long press handler (seems not possible) or for the long press listener to cancel when the recycler view scrolls (also not possible). Maybe just expose an API that allows the app to cancel long press handler and call it when the recycler view scrolls. This would be the easiest thing I think. I'm still looking into it.

**Comment by h6ah4i** [comment]
@grennis Hi. Thank you for the issue report and the pull request.

> I think the ideal solution would be to allow the app to either programmatically enter drag mode based on it's own criteria - i.e., long press handler (seems not possible) 

Yes, I also think this is the ideal solution but it is not possible because we can not obtain MotionEvent instances in long press handler...


> or for the long press listener to cancel when the recycler view scrolls (also not possible).

Yes, this is not possible also.

> Maybe just expose an API that allows the app to cancel long press handler and call it when the recycler view scrolls. This would be the easiest thing I think. I'm still looking into it.

I think this is not the best solution because the `RecyclerViewDragDropManager` is already observing scroll events, so it should cancel long press detection internally instead of exposing a new method. I have fixed this issue and created a PR #127. Try the PR and if you notice something, please let me know ;)

Thanks.

**Comment by grennis** [comment]
Yes, this is great, and the proper fix. Thank you!

**Comment by h6ah4i** [comment]
I have just released v0.8.1. Try it out! Thank you :)

**Comment by grennis** [comment]
Version 0.8.1 works great. thanks
