### ISSUE TITLE
Dragging and swiping enabled on the same area of ViewHolder

### ISSUE THREAD

**Issue by vorsichtdiekurve** [h6ah4i/android-advancedrecyclerview#128]
Hi,
Is there a way for the dragging and the swiping actions to function correctly when both actions are enabled on the whole ViewHolder? (onCheckCanStartDrag always returns true, the getSwipeableContainerView returns a view which covers the whole ViewHolder) 
Right now, the drag action seems to override and cancel the swipe action. I'd like them to cancel each other only when one action actually starts, e. g. the view is moved (dragged or swiped) a little.
Unfortunately, I need to implement this that way. Both actions are enabled on longclick.
Thanks in advance for any help.

**Comment by vorsichtdiekurve** [comment]
I resolved the issue myself. The problem is in attaching the adapter into the swipe and drag n drop manager.
It's important that the adapter is first attached to the RecyclerViewSwipeManager, otherwise the swipe action will always be overridden by the drag & drop functionality.

**Comment by h6ah4i** [comment]
FYI:  If you want to start dragging and swiping on
