### ISSUE TITLE
Item swipe completes after holder recycled

### ISSUE THREAD

**Issue by hroberts693** [h6ah4i/android-advancedrecyclerview#136]
The swipe action will continue even after the ViewHolder for the selected row is recycled - when this happens the ViewHolder provided to onSwipeItem may be invalid or bound to a different row.  Proposed fix - when the selected row's ViewHolder is recycled the swipe action is cancelled.

Base: commit 8f7af317cc93f566336f785341b93b2ec7f663b9 + http://pastebin.com/FLUeLKa2
Patch: http://pastebin.com/e5h7zCaL

**Comment by h6ah4i** [comment]
Thanks, I'll take a look at it later.

**Comment by h6ah4i** [comment]
I've just released v0.8.3 and it includes your patches. Thank you ;)
