### ISSUE TITLE
Android Studio and version 0.8.3

### ISSUE THREAD

**Issue by ivtoto** [h6ah4i/android-advancedrecyclerview#139]
I'm trying to add your library to a project and when I'm building it I receive:

    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Could not resolve all dependencies for configuration ':Android:aarLinkSources'.
    > Could not download advrecyclerview-sources.jar (com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.3): No cached version available for offline mode

Here is part of my main build.gradle:
```
buildscript {
      repositories {
        jcenter()
        maven { url 'https://raw.github.com/xujiaao/mvn-repository/master/releases' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'
        classpath 'com.github.xujiaao:aarLinkSources:1.0.0'
    }
}
```

And the module one:
```
apply plugin: 'com.android.application'
apply plugin: 'aar-link-sources'

android {
    ..........
}

dependencies {
    compile 'com.android.support:appcompat-v7:23.1.0'
    ..........
    compile ('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.3@aar'){
        transitive=true
    }
    aarLinkSources 'com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.3:sources@jar'
    ..........
}
```

Any idea of what's wrong, suggestion, solution or workaround?

Thanks in advance!

**Comment by h6ah4i** [comment]
Hi. If you are using Android Studio 1.4, you do not need to use AARLinkSouces workaround any more. I will update the instruction on README later.


ref.) https://github.com/xujiaao/AARLinkSources

> This plugin in deprecated. AndroidStudio 1.4 has this support built in.

Thanks.

**Comment by ivtoto** [comment]
Thanks for your response, it solved the issue :)
I really appreciate the your rapid response!
