### ISSUE TITLE
Refrshing the RecyclerView

### ISSUE THREAD

**Issue by rommex** [h6ah4i/android-advancedrecyclerview#140]
Hi there, thanks for your great work!

Presently I have difficulty renewing Advanced RecyclerView. I change my data and then call:

mAdapter.notifyDataSetChanged();

Within Group items and Child items I have images. Sometimes they are refreshed, sometimes not. Please help

**Comment by h6ah4i** [comment]
Hi @rommex . Could you upload an example project which can reproduce the same problem?

**Comment by rommex** [comment]
I will post the project shortly, but what are your recommendations about refreshing this widget. Let's say, from the MainActivity level?

**Comment by DarkVio** [comment]
I solved this problem creating a new onBindGroupViewHolder mProvider...

mProvider = new DataProvider();

**Comment by rommex** [comment]
@h6ah4i, sorry didn't mention you at my previous comment

**Comment by h6ah4i** [comment]
It seems that you have already know about how to refreshing RecyclerView properly.

Update data provider and then call `mAdapter.notifyDataSetChanged()`. The `onBindGropViewHolder()` and the `onBindChildViewHolder()` will be called for each items, so you can update item views in these methods.

**Comment by rommex** [comment]
Dear @h6ah4i , I beg your pardon.
I was trying to extract some portion of my code to showcase you the malfunction, but found out that I really messed with my background threads, which were making UI thread really slow.
You have a wonderful library, thanks again.
Can I delete this issue?

**Comment by h6ah4i** [comment]
@rommex Hi. I am glad to hear from you that the issue has been solved! Could you close this issue report, please?
