### ISSUE TITLE
Custom footer view can be dragged over

### ISSUE THREAD

**Issue by Tanapruk** [h6ah4i/android-advancedrecyclerview#148]
I use itemViewType to create a footer view already and that footer cannot be dragged or swiped. But, I still can drag other item over the footer view and it changes position to the drag.

How can I disable the drag over on the footer view?

**Comment by h6ah4i** [comment]
Hi. You can achieve that by overriding the `onGetItemDraggableRange()` method.

```java
@Override
public ItemDraggableRange onGetItemDraggableRange(MyViewHolder holder, int position) {
    // NOTE: "return null" means "return new ItemDraggableRange(0, getItemCount() - 1)"
    int start = 0;
    int end = getItemCount() - 2;

    return new ItemDraggableRange(start, end);
}
```

Please see the implementation of "Draggable with section" demo for the actual usage. Thanks!

ref.) https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_d_with_section/MyDraggableWithSectionItemAdapter.java#L187

**Comment by Tanapruk** [comment]
Thank you
