### ISSUE TITLE
Recycler view Duplicate content

### ISSUE THREAD

**Issue by pixelbendr** [h6ah4i/android-advancedrecyclerview#150]
Hello, my recycler view is showing duplicate content but I have enabled setHasStableIds(true); and given each created item a position by overriding getItemId. I need help. :(

**Comment by h6ah4i** [comment]
Maybe, you can use `RecyclerView.NO_ID` for duplicated items if those items are no need to make swipeable and draggable. But I have not tested it yet, so it may not work properly :(

If you need to make those items swipeable or draggable, create wrapper items object which hold reference to the same actual item object internally and implement them return non duplicated IDs.

Thanks.

**Comment by AnkitShetgaonkar** [comment]
Hi, I have a similar issue, If the child contains more than 8 items then rest items are repeated content.

**Comment by Shubhamsdr3** [comment]
Hi , thank you for this great library, However I am facing issue with duplicate contents even though I have implemented getItemId correctly I think, could you please what is going wrong here ? 
 
Here is my adapter class:  

`
  class AudioPlayingQueueAdapter(
           private val dataset: MutableList<AudioBook>,
           private var currentPlayingPosition: Int,
           private val onPlayClicked: (currentPosition: Int) -> Unit
         ): RecyclerView.Adapter<ItemAudioQueueViewHolder>(), DraggableItemAdapter<ItemAudioQueueViewHolder> {
      
          init {
              setHasStableIds(true)
          }
  
      fun setCurrentPosition(position: Int) {
          notifyItemChanged(currentPlayingPosition, false)
          this.currentPlayingPosition = position
          notifyItemChanged(position, true)
      }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ItemAudioQueueViewHolder {
        val itemBinding = ItemAudioBookBinding.inflate(LayoutInflater.from(parent.context), parent, false)
        val viewHolder = ItemAudioQueueViewHolder(itemBinding)
        itemBinding.root.setOnClickListener {
            onPlayClicked(viewHolder.absoluteAdapterPosition)
        }
        return viewHolder
    }

    override fun onBindViewHolder(holder: ItemAudioQueueViewHolder, position: Int) {
        holder.bind(dataset[position])
    }

    override fun onBindViewHolder(holder: ItemAudioQueueViewHolder, position: Int, payloads: MutableList<Any>) {
        if (payloads.isNotEmpty()) {
            holder.setPlaying(payloads[0] as Boolean)
        } else {
            super.onBindViewHolder(holder, position, payloads)
        }
    }

    override fun getItemCount() = dataset.count()

    override fun getItemId(position: Int): Long {
        val item = dataset[position]
        val id = Objects.hashCode(item.queueId).toLong()
        return id
    }

    override fun onCheckCanStartDrag(holder: ItemAudioQueueViewHolder, position: Int, x: Int, y: Int): Boolean {
        val itemView = holder.itemView
        val dragHandle = itemView.findViewById<View>(R.id.iv_drag)
        return position >= 0 && (ViewUtils.hitTest(dragHandle, x, y) || ViewUtils.hitTest(dragHandle, x, y))
    }

    override fun onGetItemDraggableRange(holder: ItemAudioQueueViewHolder, position: Int): ItemDraggableRange = ItemDraggableRange(0, dataset.size - 1)
    override fun onMoveItem(fromPosition: Int, toPosition: Int) {
        if (fromPosition != toPosition) {
            val removed: AudioBook = dataset.removeAt(fromPosition)
            dataset.add(toPosition, removed)
            notifyItemMoved(fromPosition, toPosition)
        }
    }

    override fun onCheckCanDrop(draggingPosition: Int, dropPosition: Int): Boolean {
        return true
    }

    override fun onItemDragStarted(position: Int) {
        notifyDataSetChanged()
    }

    override fun onItemDragFinished(fromPosition: Int, toPosition: Int, result: Boolean) {
        notifyDataSetChanged()
    }
} 
`

My data class: 

` 
        @Keep
         @Parcelize
      open class AudioBook(
          val bookId: Long,
          val filePath: String?,
          val bookImage: Bitmap?,
          val title: String?,
          val artist: String?,
          val duration: Long?,
          val size: Int?
      ): Parcelable {
    
        @IgnoredOnParcel
        val queueId: String = UUID.randomUUID().toString()
    
        fun deepCopy(): AudioBook {
            val jsonString = Gson().toJson(this)
            return Gson().fromJson(jsonString, AudioBook::class.java)
        }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as AudioBook

        if (bookId != other.bookId) return false
        if (filePath != other.filePath) return false
        if (bookImage != other.bookImage) return false
        if (title != other.title) return false
        if (artist != other.artist) return false
        if (duration != other.duration) return false
        return size == other.size
    }

    override fun hashCode(): Int {
        var result = bookId.hashCode()
        result = 31 * result + (filePath?.hashCode() ?: 0)
        result = 31 * result + (bookImage?.hashCode() ?: 0)
        result = 31 * result + (title?.hashCode() ?: 0)
        result = 31 * result + (artist?.hashCode() ?: 0)
        result = 31 * result + (duration?.hashCode() ?: 0)
        result = 31 * result + (size ?: 0)
        return result
    }
}`
