### ISSUE TITLE
NPE in BaseWrapperAdapter

### ISSUE THREAD

**Issue by christianlanz** [h6ah4i/android-advancedrecyclerview#151]
This is the error message I received:

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int android.support.v7.widget.RecyclerView$Adapter.getItemCount()' on a null object reference

Here you can find the stack trace: http://pastebin.com/yM6RMtQV

Looks like there is a bug in your library - check out the strack trace and please fix!

BR,
Christian

**Comment by h6ah4i** [comment]
Hi. This issue is the same as #145. Please try the latest v0.8.5 library I have just released.
