### ISSUE TITLE
bug:Samsung S3 4.1.1(genymotion) with  swipe left

### ISSUE THREAD

**Issue by oceancx** [h6ah4i/android-advancedrecyclerview#152]
support library version:23.1.1
recyclerView version:23.1.1
android-advancedrecyclerview version:0.8.5
when i swipe left,the item shift left,and i swipe back,there is grey background remainning in the item paddingLeft region.Google Nexues 5.1(genymotion ) don't have this issue

**Comment by oceancx** [comment]
can you explain something about this issue,maybe i can modify it by myself for an quick fix solution

**Comment by h6ah4i** [comment]
@oceancx Sorry, I have no idea about this issue. Also I have been busy with work and have not tried to reproduce it myself.
