### ISSUE TITLE
Bug: happens on Sumsung S3 4.1.1(genymotion),when the user remove items frequently and quickly

### ISSUE THREAD

**Issue by goceancx** [h6ah4i/android-advancedrecyclerview#154]
support library version:23.1.1
recyclerView version:23.1.1
Log:

11-27 07:33:28.467 3039-3039/com.test.mioji_support D/InCityDetailEditAdapter: onSwipeChildItem(groupPosition = 0, childPosition = 3, result = 2)
11-27 07:33:28.483 3039-3039/com.test.mioji_support D/AndroidRuntime: Shutting down VM
11-27 07:33:28.483 3039-3039/com.test.mioji_support W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa6318288)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime: FATAL EXCEPTION: main
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime: java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: ViewHolder{5380a45c position=8 id=8589934591, oldPos=-1, pLpos:-1 tmpDetached no parent}
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:4631)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1091)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.access$6200(RecyclerView.java:144)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:9546)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:10022)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v7.widget.SimpleItemAnimator.dispatchMoveFinished(SimpleItemAnimator.java:266)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.impl.ItemMoveAnimationManager.dispatchFinished(ItemMoveAnimationManager.java:54)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.impl.ItemMoveAnimationManager.dispatchFinished(ItemMoveAnimationManager.java:24)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager$BaseAnimatorListener.onAnimationEnd(BaseItemAnimationManager.java:227)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:47)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:973)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1018)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.animation.ValueAnimator.cancel(ValueAnimator.java:946)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.view.ViewPropertyAnimator.animatePropertyBy(ViewPropertyAnimator.java:825)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.view.ViewPropertyAnimator.animateProperty(ViewPropertyAnimator.java:781)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.view.ViewPropertyAnimator.translationY(ViewPropertyAnimator.java:530)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompatICS.translationY(ViewPropertyAnimatorCompatICS.java:38)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.translationY(ViewPropertyAnimatorCompat.java:382)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompat.translationY(ViewPropertyAnimatorCompat.java:743)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator$SwipeDismissItemMoveAnimationManager.onAnimationCancel(SwipeDismissItemAnimator.java:354)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator$SwipeDismissItemMoveAnimationManager.onAnimationCancel(SwipeDismissItemAnimator.java:306)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager$BaseAnimatorListener.onAnimationCancel(BaseItemAnimationManager.java:236)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationCancel(ViewPropertyAnimatorCompatJB.java:42)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationCancel(ViewPropertyAnimator.java:955)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.animation.ValueAnimator.cancel(ValueAnimator.java:943)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.view.ViewPropertyAnimator.cancel(ViewPropertyAnimator.java:358)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompatICS.cancel(ViewPropertyAnimatorCompatICS.java:102)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.cancel(ViewPropertyAnimatorCompat.java:462)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at android.support.v4.view.ViewPropertyAnimatorCompat.cancel(ViewPropertyAnimatorCompat.java:1049)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.endAnimation(ItemSlidingAnimator.java:387)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.animateSlideInternal(ItemSlidingAnimator.java:350)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.animateSlideInternalCompat(ItemSlidingAnimator.java:250)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime:     at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.slideToSpecifiedPositionInternal(ItemSlidingAnimator.java:153)
11-27 07:33:28.515 3039-3039/com.test.mioji_support E/AndroidRuntime: 	at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.slideToDefaultPosition(ItemSlidingAnimator.java:67
11-27 07:33:28.555 3039-3042/com.test.mioji_support D/dalvikvm: GC_CONCURRENT freed 705K, 9% free 12968K/14215K, paused 12ms+7ms, total 39ms

**Comment by oceancx** [comment]
support library version:23.1.1
recyclerView version:23.1.1

**Comment by oceancx** [comment]
can you explain something about this issue,maybe i can modify it by myself for an quick fix solution

**Comment by h6ah4i** [comment]
@oceancx Sorry, I have no idea about this issue. Also I have been busy with work and have not tried to reproduce it myself.
