### ISSUE TITLE
Shadow question

### ISSUE THREAD

**Issue by yarolegovich** [h6ah4i/android-advancedrecyclerview#157]
Hi, I'm looking through examples and can't understand how it works
```
if (supportsViewElevation()) {
            // Lollipop or later has native drop shadow feature. ItemShadowDecorator is not required.
        } else {
            mRecyclerView.addItemDecoration(new ItemShadowDecorator((NinePatchDrawable) ContextCompat.getDrawable(getContext(), R.drawable.material_shadow_z1)));
        }
```
Here you reference R.drawable.material_shadow_z1, that looks like this 
```
<nine-patch xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:src="@drawable/material_shadow_z1_xhdpi"
    tools:ignore="unused" />
```
But where does @drawable/material_shadow_z1_xhdpi exist?

**Comment by h6ah4i** [comment]
Hi. Take a look into the `drawable-nodpi` directory.

https://github.com/h6ah4i/android-advancedrecyclerview/tree/master/example/src/main/res/drawable-nodpi

Some minor density version of `material_shadow_z1` share a same ninepatch file.

- ldpi, tvdpi, hdpi  -> mdpi

Thanks.

**Comment by yarolegovich** [comment]
Thanks
