### ISSUE TITLE
swiping on any item only moves index 1

### ISSUE THREAD

**Issue by faultylogic** [h6ah4i/android-advancedrecyclerview#159]
Only the first item show a swiping animation no matter the position.

**Comment by h6ah4i** [comment]
Hi. Have you implemented  the `getItemId()` method of your adapter class? It should returns unique number among each items and the number must be stable (must not be changed even after removed or reordered). Thanks.

**Comment by faultylogic** [comment]
Thanks that seems to have fixed my issue much appreciated :+1:
