### ISSUE TITLE
How can i get the isAllExpanded / isAllCollapsed methods? Question

### ISSUE THREAD

**Issue by AndrejSperling** [h6ah4i/android-advancedrecyclerview#161]
How can i get the isAllExpanded / isAllCollapsed methods from ExpandablePositionTranslator.java class, since ExpandableRecyclerViewWrapperAdapter dont provide a public method?

**Comment by h6ah4i** [comment]
Hi. Unfortunately, there is no way to call those methods for now.

I think it is a good idea adding these methods to `RecyclerViewExpandableItemManager`.

- `getExpandedGroupsCount()`
- `isAllGroupsExpanded()`
- `isAllGroupsCollapsed()`

**Comment by AndrejSperling** [comment]
Thanks! =)
