### ISSUE TITLE
Dragging with only 2 items in list lags significantly more than if it had more than 2 items..

### ISSUE THREAD

**Issue by marcochin** [h6ah4i/android-advancedrecyclerview#163]
![two_item_lag](https://cloud.githubusercontent.com/assets/11529866/11760283/7eeebb64-a04a-11e5-95dc-a5d6b6f8bda9.png)

Note: Item 1 is larger then the rest of the items.

In Fig. A, if I play around by dragging item 2 over item 1 and back again (not letting go of drag in the process), you will see a noticeable stop in the animation as if something were blocking it. This "blockage" disappears when there are at least 3 items in the list (Fig. B). 

Also this blockage only occurs if you drag the SMALLER item over the bigger item. Dragging the big item over the small item works fine.

Anyways, just wanted to let you know maybe for a future fix. Thanks for your work on this amazing library!

**Comment by h6ah4i** [comment]
Hi. Thanks for reporting the issue. I will take a look at it.
