### ISSUE TITLE
Swipe state not working properly

### ISSUE THREAD

**Issue by okaa-pi** [h6ah4i/android-advancedrecyclerview#170]
Hi!

First of all, I'm sorry if I make mistakes but english is not my first language, so I'll do my best to explain what is the problem.

I have a recyclerview with two different viewtypes, headers and items.

The items should be swipeable left and right. Both actions should delete the item from the list.

What I'm able to do:
Get the swipe on the items, from left and right, with colors, and actions.

The problem:
When an item is removed from the list, instead of going straight to the outside of the screen, the next item inherit the "slide" state, and come back to its initial state.

A video might be easier to understand:
![oneplus2lmy47vdylancabal01132016163549](https://cloud.githubusercontent.com/assets/1364175/12298797/4015b5c6-ba14-11e5-891e-5feffbc3487a.gif)

Here is how I set the adapter:

    mLeaveRequestAdapter = new LeaveRequestsAdapter(getActivity());
    mRecyclerViewSwipeManager = new RecyclerViewSwipeManager();

    final GeneralItemAnimator animator = new SwipeDismissItemAnimator();
    animator.setSupportsChangeAnimations(false);

    mRecyclerViewTouchActionGuardManager  = new RecyclerViewTouchActionGuardManager();
    mRecyclerViewTouchActionGuardManager.setInterceptVerticalScrollingWhileAnimationRunning(true);
    mRecyclerViewTouchActionGuardManager.setEnabled(true);

    RecyclerView.Adapter mWrappedAdapter = mRecyclerViewSwipeManager.createWrappedAdapter(adapter);
    mRecyclerView.setAdapter(mWrappedAdapter);
    mRecyclerView.setItemAnimator(animator);
    mRecyclerViewTouchActionGuardManager.attachRecyclerView(mRecyclerView);
    mRecyclerViewSwipeManager.attachRecyclerView(mRecyclerView);

This is the swipe part of the adapter:

    @Override
    public SwipeResultAction onSwipeItem(LeaveRequestViewHolder holder, int position, int result) {
        switch (result) {
            case SwipeableItemConstants.RESULT_SWIPED_RIGHT:
                Log.i("debug", "Swiped right");
                return new SwipeResultDeleteAction(this, position);

            case SwipeableItemConstants.RESULT_SWIPED_LEFT:
                Log.i("debug", "Swiped left");
                return new SwipeResultDeleteAction(this, position);

            case SwipeableItemConstants.RESULT_CANCELED:
                Log.i("debug", "Swipe cancelled");
            default:
                if (position != RecyclerView.NO_POSITION) {
                    return new UnpinResultAction();
                } else {
                    return null;
                }
        }
    }

    @Override
    public int onGetSwipeReactionType(LeaveRequestViewHolder holder, int position, int x, int y) {
        return SwipeableItemConstants.REACTION_CAN_SWIPE_BOTH_H;
    }

    @Override
    public void onSetSwipeBackground(LeaveRequestViewHolder holder, int position, int type) {
        int bgRes = 0;
        switch (type) {
            case SwipeableItemConstants.DRAWABLE_SWIPE_NEUTRAL_BACKGROUND:
                bgRes = R.drawable.bg_swipe_item_neutral;
                break;
            case SwipeableItemConstants.DRAWABLE_SWIPE_LEFT_BACKGROUND:
                bgRes = R.drawable.bg_swipe_item_deny;
                break;
            case SwipeableItemConstants.DRAWABLE_SWIPE_RIGHT_BACKGROUND:
                bgRes = R.drawable.bg_swipe_item_accept;
                break;
        }

        holder.itemView.setBackgroundResource(bgRes);
    }

    private static class SwipeResultDeleteAction extends SwipeResultActionRemoveItem {
        private LeaveRequestsAdapter mAdapter;
        private final int mPosition;

        SwipeResultDeleteAction(LeaveRequestsAdapter adapter, int position) {
            mAdapter = adapter;
            mPosition = position;
        }

        @Override
        protected void onPerformAction() {
            super.onPerformAction();
            
            mAdapter.myRequests.remove(mPosition);
            mAdapter.notifyItemRemoved(mPosition);
        }

        @Override
        protected void onSlideAnimationEnd() {
            super.onSlideAnimationEnd();
        }

        @Override
        protected void onCleanUp() {
            super.onCleanUp();
            mAdapter = null;
        }
    }

    private static class UnpinResultAction extends SwipeResultActionDefault {

        UnpinResultAction() {
        }

        @Override
        protected void onPerformAction() {
            super.onPerformAction();
        }

        @Override
        protected void onCleanUp() {
            super.onCleanUp();
        }
    }

I don't know what to do at this point. 
Hope my explanations were clear.

Thanks for any help.

**Comment by h6ah4i** [comment]
Hi. Sorry for the late reply :disappointed: 

Have you implemented the `getItemId()` method as it returns **stable* ID for each items? The app behavior looks like the `getItemId()` method returns just a `position`.

```java
long getItem(int position) {
   // return position; // this is not a stable ID!
   return getItem(position).getId();    // should returns stable value. IDs have to be kept the same value even after its position has been changed.
}
```

**Comment by okaa-pi** [comment]
No problem for the late reply dude. We all have work to do.

You're right, I was returning the position. Never really used the ID before. 
I changed it to return the hashcode of the item's BDD ID.

It works now! You're a genius! Thanks a lot ;)
