### ISSUE TITLE
Remove Separators

### ISSUE THREAD

**Issue by jackellenberger** [h6ah4i/android-advancedrecyclerview#171]
Is there a way currently to remove separators between recycler view items? At the moment when the recyclerview has items one on top of another, there appears to be a 1px or so grey line. With ListViews one can use 
```
getListView().setDivider(null);
getListView().setDividerHeight(0);
```
or
`android:divider="@null"` in xml. Is there something similar already implemented?

**Comment by h6ah4i** [comment]
Hi. `RecyclerView` does not have has native item divider feature, instead it provides more flexible mechanism called `ItemDecoration`. The demo app uses `SimpleListDividerDecorator` class to draw item dividers, so if you want to hide them just remove the line attaching the decorator to `RecyclerView`.

```java
mRecyclerView.addItemDecoration(new SimpleListDividerDecorator(...));

to

// mRecyclerView.addItemDecoration(new SimpleListDividerDecorator(...)); 
```
