### ISSUE TITLE
fragment scrolled to top

### ISSUE THREAD

**Issue by siavashabdoli** [h6ah4i/android-advancedrecyclerview#175]
I have xml like this:

    <LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
        <ScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/scrollView1">
            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">
                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="1000px"
                     />
            <RelativeLayout
                android:id="@+id/container"
                android:layout_width="match_parent"
                android:layout_height="1000px" />
            </LinearLayout>
        </ScrollView>

</LinearLayout>

I add fragments of "expandable(add/remove items)" sample to container
when activity launch scrollView1 already scrolled to down! I can't find why it happened

**Comment by siavashabdoli** [comment]
actually I want to have some layout above of my recycler view, if there is clearer way let me know :)

**Comment by h6ah4i** [comment]
Hi. That seems not my library issue. I found a helpful post on StackOverflow and it solve the problem.


#### Solution

Add `android:descendantFocusability="blocksDescendants"` attribute to the `RelativeLayout` of container view for Fragments.

```xml
<RelativeLayout
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="1000px"
    android:descendantFocusability="blocksDescendants" />
```

---

ref.) [How to prevent a scrollview from scrolling to a webview after data is loaded?](http://stackoverflow.com/questions/9842494/how-to-prevent-a-scrollview-from-scrolling-to-a-webview-after-data-is-loaded)

**Comment by siavashabdoli** [comment]
It works. thanks a lot ;)
