### ISSUE TITLE
Question: borders and shadows are lost in Android 5.1

### ISSUE THREAD

**Issue by rommex** [h6ah4i/android-advancedrecyclerview#177]
Cards have border and shadows in Android 4.4 but in Lollipop they are gone. I must be doing smth wrong but could you help please?

**Comment by h6ah4i** [comment]
Hi. The example app uses `android:elevation` attribute with `android:outlineProvider="bounds"`.

https://github.com/h6ah4i/android-advancedrecyclerview/blob/ff7e2290461f2aee04a850aba30e947965d2b815/example/src/main/res/values-v21/styles.xml#L18

Also you can use `ItemShadowDecorator` for API level 21+ which is used for older API level devices. 

https://github.com/h6ah4i/android-advancedrecyclerview/blob/ff7e2290461f2aee04a850aba30e947965d2b815/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_d/RecyclerListViewFragment.java#L86

Thanks.

**Comment by rommex** [comment]
Thank you!

**Comment by Alpha2J** [comment]
thanks very much!!  It has solved my problem perfectly!!
