### ISSUE TITLE
No notification when item is dropped to initial position

### ISSUE THREAD

**Issue by cookieKeks** [h6ah4i/android-advancedrecyclerview#179]
Hi,
I am using your drag and drop feature in a GridView. To prevent the screen from rotating while an item is dragged I lock the screen to the current rotation in DraggableItemAdapter.onCheckCanStartDrag and unlock it in DraggableItemAdapter.onMoveItem in my implementation of the DraggableItemAdapter. However I don't get a call to onMoveItem if the from-position and the to-position are equal, so I cannot unlock the screen when the dragged item is dropped back to its initial position. So my question is: Do you have a workaround for that or could you provide information when the dragged item is dropped at the same position?

**Comment by h6ah4i** [comment]
Hi. You can use `RecyclerViewDragDropManager.OnItemDragEventListener` to observe drag & drop event. It provides `onItemDragStarted()` and `onItemDragFinished()` callbacks that you are looking for :wink: 

```java
mDragDropMgr.setOnItemDragEventListener(
    new RecyclerViewDragDropManager.OnItemDragEventListener{
        @Override
        void onItemDragStarted(int position) {
            // lock screen rotation
        }

        @Override
        void onItemDragPositionChanged(int fromPosition, int toPosition) {}

        @Override
        void onItemDragFinished(int fromPosition, int toPosition, boolean result) {
            // unlock screen rotation
        }
    });
```

**Comment by cookieKeks** [comment]
Thank you very much! That solved it.
