### ISSUE TITLE
onlick child item?

### ISSUE THREAD

**Issue by tuannd2011** [h6ah4i/android-advancedrecyclerview#18]
Can you support onlick child item? ( not swip )
Demo: click one row then make a toast return position item

**Comment by h6ah4i** [comment]
Thanks for your suggestion. I'll improve the sample code later.

FYI: You can implement it by the following steps;
1. set `View.OnClickListener` for each item views (ViewHolder.itemView)
2. In `onClick()` method, obtain flat item position by using `ViewHolder.getLayoutPosition()`
3. Convert to group and child item positions by using `getExpandablePosition()`, `getPackedPositionGroup()` and `getPackedPositionChild()` methods of `RecyclerViewExpandableItemManager` class.

**Comment by psousa50** [comment]
I think this solution doesn't work because the RecyclerView...Managers consumes the touch events (in onInterceptTouchEvent) and doesn't allow them to reach the child views. Am I wrong?

**Comment by psousa50** [comment]
Sorry, I was wrong, my mistake, it works.
