### ISSUE TITLE
GPlay Analytics craches with AdvancerRecycylerView

### ISSUE THREAD

**Issue by juniorJaffa** [h6ah4i/android-advancedrecyclerview#184]
Hi,
Significantly Google Play service-analytics and this advanced recycler view does not work together. 
I tried this dependency variously up and down to assure and really these two dependencies makes bug.
AndroidRuntime: FATAL EXCEPTION: main  java.lang.NoClassDefFoundError:
sk.doxxbet.analytics.AnalyticsTrackers$1
build.gradle
compile 'com.google.android.gms:play-services-analytics:8.4.0'
.
.
compile ('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.5@aar'){
        transitive=true
    }

also have tried:
compile ('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.0@aar'){
        transitive=true
    }
compile ('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.5'){
        transitive=true
    }
compile ('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.0'){
        transitive=true
    }

I remove either Google Analytics or Advanced Recycler View and it works.

**Comment by h6ah4i** [comment]
Hi. Thank you for the report. I will check this as soon as possible.

**Comment by h6ah4i** [comment]
@juniorJaffa Could you give me some additional info to investigate the issue? I cannot reproduce the same issue on my setup; I have an app project which uses `play-services-analytics:8.4.0` and `advrecyclerview:0.8.2`, I confirmed it works fine without any problems.

- Gradle version
- Version of Gradle Plugin for Android ()
- Android Build Tools version
- compileSdkVersion
- Dump of `./gradlew app:dependencies`

**Comment by juniorJaffa** [comment]
Gradle version: **2.8**
Version of Gradle Plugin for Android (): **1.5.0**
Android Build Tools version: **23.0.2**
compileSdkVersion: **API 23: Android 6.0 (Marshmallow)**
Dump of ./gradlew app:dependencies:
_junior:android-studio $ cd .gradle/
junior:.gradle $ ls -la
total 0
drwxr-xr-x   5 junior  staff  170 Feb  2 20:29 .
drwxr-xr-x  15 junior  staff  510 Feb  2 20:38 ..
drwxr-xr-x   3 junior  staff  102 Feb  2 20:29 2.10
drwxr-xr-x   3 junior  staff  102 Dec  3 15:08 2.4
drwxr-xr-x   3 junior  staff  102 Nov 30 09:00 2.8_

app:dependencies:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        // Enabling multidex support.
        multiDexEnabled true
        applicationId "sk.doxxbet"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            // runProguard false ** NOT USED ANYMORE, replaced by minifyEnabled
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
    productFlavors {
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    dexOptions {
        incremental true
        preDexLibraries false
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
    // Card View and Recycler View Library
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'

    // google analytics
    compile 'com.google.android.gms:play-services-analytics:8.4.0'
    // google maps
    compile 'com.google.android.gms:play-services-maps:8.4.0'
    // spring rest
    compile 'org.springframework.android:spring-android-rest-template:2.0.0.M1'
    // json
    compile 'com.fasterxml.jackson.core:jackson-databind:2.6.1'

    // library of Joda-Time built for Android
    //compile 'net.danlew:android.joda:2.9.2'
    //compile 'joda-time:joda-time:2.9.2'

    **_compile ('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.6@aar'){
        transitive=true
    }
_**
    // drawer
    compile('com.mikepenz:materialdrawer:4.5.2@aar') {
        transitive = true
    }
    // menu badge
    compile 'com.mikepenz:actionitembadge:3.2.0@aar'
    // Android Icons
    compile 'com.mikepenz:iconics-core:2.5.0@aar'
    //Google Material Icons
    //FontAwesome
    compile 'com.mikepenz:google-material-typeface:2.2.0.1@aar'
    compile 'com.mikepenz:fontawesome-typeface:4.4.0.1@aar'

    // ui
    compile 'com.jakewharton:butterknife:7.0.1'
    provided 'org.projectlombok:lombok:1.16.6'
    provided 'org.glassfish:javax.annotation:10.0-b28'

    // universal image loader
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'

    // Canary Leak
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.3.1'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.3.1'


    // Unit testing dependencies
    testCompile 'junit:junit:4.12'
    // Set this dependency if you want to use Mockito
    testCompile 'org.mockito:mockito-core:1.10.19'
    // Set this dependency if you want to use Hamcrest matching
    androidTestCompile 'org.hamcrest:hamcrest-library:1.1'

    // guava
    compile 'com.google.guava:guava:18.0'

    // oto -event bus
    compile 'com.squareup:otto:1.3.8'

    // fab action button
    compile 'com.github.clans:fab:1.6.2'

    // ripple effects
    //compile 'com.github.traex.rippleeffect:library:1.3'

//    compile files('libs/gson-2.2.4.jar')
//    compile files('libs/signalr-client-sdk.jar')
//    compile files('libs/signalr-client-sdk-android.jar')
}


repositories {
    maven {
        url 'http://repo.spring.io/milestone'
    }
}

**Comment by h6ah4i** [comment]
@juniorJaffa Thanks. But I still cannot reproduce the same issue though. I guess the `NoClassDefFoundError` occurs **only on release build**, is it right? If so, I also need your `proguard-rules.pro` file to continue to investigate the issue.

My experiment AS project is here: https://github.com/h6ah4i/AdvancedRecyclerViewIssue184
