### ISSUE TITLE
Only have one group expanded at a time

### ISSUE THREAD

**Issue by intrications** [h6ah4i/android-advancedrecyclerview#19]
Is there a way to automatically close all the other groups when one is expanded?

**Comment by h6ah4i** [comment]
That is possible. You can use these methods to control the behavior when clicked the group item.

> - `RecyclerViewExpandableItemManager.expandGroup(int groupPosition)`
> - `RecyclerViewExpandableItemManager.collapseGroup(int groupPosition)`
> 
> FYI: If you don't want to expand/collapse a group when touching the item, please implement the `onCheckCanExpandOrCollapseGroup()` method always returns false.

ref.) Force expand/colapse #11

**Comment by intrications** [comment]
Thanks. This is what I had tried but made another mistake in the code which stopped it working properly.
