### ISSUE TITLE
Crash isGroupExpanded Need a fix

### ISSUE THREAD

**Issue by manuel-sejourne** [h6ah4i/android-advancedrecyclerview#190]
Hi !

In my app users have an issue with your library, you can find the stacktrace below : **# ArrayIndexOutOfBoundsException  
com.h6ah4i.android.widget.advrecyclerview.expandable.ExpandablePositionTranslator.isGroupExpanded(SourceFile:185)**
ArrayIndexOutOfBoundsException  
com.h6ah4i.android.widget.advrecyclerview.expandable.ExpandablePositionTranslator.isGroupExpanded(SourceFile:185)**

java.lang.ArrayIndexOutOfBoundsException: length=512; index=-1
!	1	at com.h6ah4i.android.widget.advrecyclerview.expandable.ExpandablePositionTranslator.isGroupExpanded(SourceFile:185)
2	at com.h6ah4i.android.widget.advrecyclerview.expandable.ExpandableRecyclerViewWrapperAdapter.onTapItem(SourceFile:591)
3	at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager.handleActionUpOrCancel(SourceFile:282)
4	at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager.onInterceptTouchEvent(SourceFile:218)
5	at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager$1.onInterceptTouchEvent(SourceFile:95)
6	at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(SourceFile:2161)
7	at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(SourceFile:2207)
8	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
9	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
10	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
11	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
12	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
13	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
14	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
15	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
16	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
17	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
18	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
19	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
20	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
21	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
22	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
23	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
24	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
25	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2607)
26	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1779)
27	at android.app.Activity.dispatchTouchEvent(Activity.java:2846)
28	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:60)
29	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:60)
30	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2568)
31	at android.view.View.dispatchPointerEvent(View.java:9003)
32	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4209)
33	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4072)
34	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)
35	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3680)
36	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3646)
37	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3763)
38	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3654)
39	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3820)
40	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)
41	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3680)
42	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3646)
43	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3654)
44	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)
45	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5910)
46	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5884)
47	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5855)
48	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6000)
49	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
50	at android.os.MessageQueue.nativePollOnce(Native Method)
51	at android.os.MessageQueue.next(MessageQueue.java:143)
52	at android.os.Looper.loop(Looper.java:122)
53	at android.app.ActivityThread.main(ActivityThread.java:5910)
54	at java.lang.reflect.Method.invoke(Native Method)
55	at java.lang.reflect.Method.invoke(Method.java:372)
56	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
57	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by h6ah4i** [comment]
Hi. Thanks for the issue report. However I do not have any ideas to reproduce the same bug. Could you upload a sample code?

**Comment by manuel-sejourne** [comment]
It is ok.

I needed to add this when I changed the adapter :
   
 if (recyclerViewExpandableItemManager != null) {
            recyclerViewExpandableItemManager.release();
            recyclerViewExpandableItemManager = null;
       }
