### ISSUE TITLE
Is there any way to cancel long press detection while swiping a item

### ISSUE THREAD

**Issue by joeyps** [h6ah4i/android-advancedrecyclerview#194]
I enabled long press dragging and swiping at the same time. When I started to swipe a item, it would also start to drag a item, so I could not swipe the item in the situation. I've tried to call RecyclerViewDragDropManager.cancelDrag when I started to swipe, but it would defer the cancel message, so it still did not work.

**Comment by h6ah4i** [comment]
Hmm... that seems strange `cancelDrag` should work in such case. 

```java
mDragDropManager.setInitiateOnLongPress(true);
mDragDropManager.setInitiateOnMove(false);

mSwipeManager.setOnItemSwipeEventListener(new RecyclerViewSwipeManager.OnItemSwipeEventListener() {
    @Override
    public void onItemSwipeStarted(int position) {
        mDragDropManager.cancelDrag();
    }
});
```

Please check the following repository for more details.

https://github.com/h6ah4i/Phoenix/tree/advrecyclerview_integration_demo

**Comment by joeyps** [comment]
It seems that I misused the function. I called cancelDrag after DraggableItemAdapter.onSwipeItem. Now I use the implementation above, it works pretty well.

Thank you very much, and thank you for this awesome lib :+1:

**Comment by h6ah4i** [comment]
:+1: :smile:
