### ISSUE TITLE
[HELP] Swipe animation not like example

### ISSUE THREAD

**Issue by nafuto** [h6ah4i/android-advancedrecyclerview#199]
I'm using swipe on recyclerview. I set `holder.setSwipeItemHorizontalSlideAmount(0)` at `onBindViewHolder` but animation not like example. If not set `holder.setSwipeItemHorizontalSlideAmount(0)`, item view doesn't remove. Here is my video that shows problem:
[Youtube Link](https://youtu.be/DkS0wAPf0-8)
Please help me :'( 
よろしくお願いします。

**Comment by h6ah4i** [comment]
Hi. It seems that your adapter does not implement `getItemId()` method properly.

```java
  @Override
    public long getItemId(int position) {
        // return position; <- this is not stable!

        // should returns stable value. IDs have to be kept the same value 
        // even after its position has been changed.
        return mItems.get(position).getId();
    }
```

related issues:
- Help!! #180
- Swipe state not working properly #170
- swiping on any item only moves index 1 #159
- Unnecessary animation on drag #83
- Position Changing Between List Item #22
- Issues with stable ids #7
- Repeated animation problem #5

**Comment by nafuto** [comment]
本当に助かりました。ありがとうございます。
