### ISSUE TITLE
Play Store Video

### ISSUE THREAD

**Issue by jpshelley** [h6ah4i/android-advancedrecyclerview#2]
Not a very big deal, but the play store video when viewed from a Mobile Device (Web is fine) looks like this and the entire screen is cut off. Play store plays all videos in landscape I believe.
- Just thought I'd let you be aware of the issue @h6ah4i 
[Using an HTC One M7]

![screenshot_2015-02-02-11-49-20](https://cloud.githubusercontent.com/assets/2798846/6005680/df41c1b0-aad1-11e4-9922-fd3326d61aab.png)

**Comment by h6ah4i** [comment]
Thank you for the issue report.  I made a new demonstration video for v0.6.0 and fixed the issue.
