### ISSUE TITLE
 animator.setSupportsChangeAnimations not accessible in buildToolsVersion '23.0.2' 

### ISSUE THREAD

**Issue by BilalSiddiqui** [h6ah4i/android-advancedrecyclerview#201]
After changing targetSdkVersion 23 and  buildToolsVersion '23.0.2', setSupportsChangeAnimations not accessible.
Problem also addressed here.
http://android-developers.blogspot.com/2015/10/android-support-library-231.html

**Comment by h6ah4i** [comment]
@BilalSiddiqui Hi. I think Advanced RecyclerView v0.8.2+ (latest: 0.8.6) is already compatible with support library v23.1.0. Which version of this library do you use?

**Comment by h6ah4i** [comment]
@BilalSiddiqui Any progress on this issue?

**Comment by BilalSiddiqui** [comment]
Working fine after update.Thanks
