### ISSUE TITLE
How to download only swipeable with gradle?

### ISSUE THREAD

**Issue by Nominalista** [h6ah4i/android-advancedrecyclerview#203]
Your awesome library is quite big, and with known issue of 65k methods it's hard to using it. Is it possible to download only part of your library? I mean e.g. only swipeable part?

**Comment by livotov** [comment]
Turn on multidex support to get rid of 65K limit. Sooner or later your project will reach this limit anyway.

Also, if you're using google services, try including per-service deps instead of all-in-one dependency - this will greatly decrease method count in your app, so instead of

```
compile 'com.google.android.gms:play-services:8.4.0'
```

you can write something like this (remove the unused services)

```
    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    compile 'com.google.android.gms:play-services-location:8.4.0'
    compile 'com.google.android.gms:play-services-maps:8.4.0'
    compile 'com.google.android.gms:play-services-analytics:8.4.0'
```

**Comment by Nominalista** [comment]
I know that, and I am using only packages which I use. And really multidex is not what I want. Look at google i/o application - it's optimizing proguard, but it has huge number of dependencies.

**Comment by h6ah4i** [comment]
@Nominalista Hi. This library has about 1200 methods. Is it too much for you?

Matybe, it is possible to shrink to 550 .. 700 methods if swiping feature only. I guess making library divided per function increases managing cost, so I do not have a plan to do this for now.

<img src="https://cloud.githubusercontent.com/assets/2552365/13515505/3b296978-e1f5-11e5-861e-610f0ed25451.png" width="350" />
source.) http://inloop.github.io/apk-method-count/

**Comment by Nominalista** [comment]
Thank you for your time and response. I left library with 1200 methods.
