### ISSUE TITLE
Drag n Drop on Samsung S5 and Moto G

### ISSUE THREAD

**Issue by tarunism** [h6ah4i/android-advancedrecyclerview#206]
For long recycler list, Drag and drop are not working on Samsung S5 and Moto G.
I have recently upgraded lib to 0.8.6 let me know if any new change has to be added.

**Comment by h6ah4i** [comment]
@tarunium Hi. Could you upload a sample project which can reproduce the same issue?

**Comment by tarunism** [comment]
Hi,

Sorry it was my mistake. On said devices hitTest was not getting performed because of some checks.
Now Its working fine.

Thanks.
