### ISSUE TITLE
NoSuchMethodError???

### ISSUE THREAD

**Issue by waikchiu5** [h6ah4i/android-advancedrecyclerview#209]
I followed the demo_d folder and tried to test the Drag and drop example.
I cannot not run the application. I can compile successfully on Android Studio. When i upload to the mobile device. The application will force close immediately. 
The error is here:
[https://codeshare.io/VDYW6](https://codeshare.io/VDYW6)

Only 3 java in my Test application:
MyItem class:
[https://codeshare.io/27VxM](https://codeshare.io/27VxM) 

MyDraggableItemAdapter class
[https://codeshare.io/BTmHi](https://codeshare.io/BTmHi)

MainActivity class:
[https://codeshare.io/wMj4p](https://codeshare.io/wMj4p)

am i wrong??

**Comment by waikchiu5** [comment]
is the animator problem?
When i declare :
`final GeneralItemAnimator animator = new RefactoredDefaultItemAnimator();`

It will show

> java.lang.NoClassDefFoundError: com.h6ah4i.android.widget.advrecyclerview.animator.RefactoredDefaultItemAnimator

So , i comment this line and
`mRecyclerView.setItemAnimator(animator);`

and declare as
`mRecyclerView.getItemAnimator().setSupportsChangeAnimations(false);`

However, logcat will display NoSuchMethodError

**Comment by h6ah4i** [comment]
@waikchiu5 Hi. Which version of `com.android.support:recyclerview-v7` do you use? It seems a version mismatch of `Advanced RecyclerView` with support library.

**Comment by waikchiu5** [comment]
@h6ah4i Thank you for your reply
I use this these two version
`compile 'com.android.support:recyclerview-v7:22.2.0'
    compile 'com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.6@aar'`

**Comment by h6ah4i** [comment]
@waikchiu5 Okay. Here is a summary of compatibility info with support library.

| `com.android.support:recyclerview-v7` | Advanced RecyclerView |
|---|---|
| v22.x | up to **v0.8.1** | 
| v23.0.x | up to **v0.8.1** | 
| v23.1.x | up to **v0.8.6** | 
| v23.2.0 | not recommended; #202 |
| **v23.2.1** (latest: March 21, 2016) | up to **v0.8.6** |

ref.) https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/RELEASE-NOTES.md

**Comment by waikchiu5** [comment]
@h6ah4i 
Oh!I forgot check the version of RecyclerView!
Sorry for my stupid question.
