### ISSUE TITLE
Expand ChildView : how can to change the textview color.

### ISSUE THREAD

**Issue by thanhsontube** [h6ah4i/android-advancedrecyclerview#217]
I can not change the color of ChildView of Expand Recycler view.
Is there anyway to do it? setTextColor does not work. 

` @Override
    public void onBindChildViewHolder(final MyChildViewHolder holder, int groupPosition, int childPosition, int viewType)
    {
        // group item
        
        holder.mName.setText(dish.getName());
        holder.mName.setTextColor(Color.RED);`

**Comment by thanhsontube** [comment]
Sorry, I got a mistake.

**Comment by sadaq19** [comment]
Hello ! Please, thanhsontube, I'm facing same issue (setTextColor). Do you succesfully resolved it ? If yes, please help. Or anybody that would kindly help Thanks...
