### ISSUE TITLE
Works with StaggeredGridLayoutManager?

### ISSUE THREAD

**Issue by kuffs** [h6ah4i/android-advancedrecyclerview#219]
Can't see anything that says it does or does not work.

Would appreciate confirmation so I don't spend days trying to get it to work if it simply is not possible.

Dragging seems to currently work, it just won't drop.

Thank you.

**Comment by h6ah4i** [comment]
Hi. Thank you for good question. 
This library does not support drag&drop feature for now, but I guess that feature can be implemented because Google's Keep app implement it based on RecyclerView (maybe). I will try it on this weekend.

**Comment by h6ah4i** [comment]
Hi @kuffs. I have just pushed an experimental branch which supports StaggeredGridLayoutManager.

- https://github.com/h6ah4i/android-advancedrecyclerview/tree/feature/support_staggered_grid_drag_drop

<img src="https://cloud.githubusercontent.com/assets/2552365/14230554/406b7cfe-f998-11e5-8cb7-b703ac28cf57.png" width="150" />

---

You can try the latest library through JitPack:

```gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.h6ah4i:android-advancedrecyclerview:d9264bb4e992762c2ce90a6a2f99c4d3228add40'
}
```

**Comment by kuffs** [comment]
I'll give that a try. Thank you.
