### ISSUE TITLE
Position Changing Between List Item

### ISSUE THREAD

**Issue by huteri** [h6ah4i/android-advancedrecyclerview#22]
Hi, I have problem implementing expandable list with fixed recyclerview. Please see the video https://www.youtube.com/watch?v=fkcmtkZz3zo

The way I do it is to resize recyclerview and recalculate the height based on how much item is expanded. 
Do you think it's possible to fix this issue?

**Comment by h6ah4i** [comment]
Hi. Have you implemented the getGroupId() and getChildId() methods properly that return stable IDs?

**Comment by huteri** [comment]
Ah thanks, it's because I set the ids with random number.

**Comment by h6ah4i** [comment]
:beer:

**Comment by vevo-kevin-kawai** [comment]
This worked great!  I implemented  adapter.getItemId(position) incorrectly because I was adding the position value to my otherwise stable unique item ID.  Using the position made it unstable.
