### ISSUE TITLE
How to implement Expandable + Draggable + Swipeable in horizontal ScrollView

### ISSUE THREAD

**Issue by ArunPandiyan** [h6ah4i/android-advancedrecyclerview#222]
I tried to it in horizontal mode by changing layout manager to Horizontal. But the child views animating from left to right. What i need is to have parent which animates down for child? How can i do that? Thanks a lot for library like this. Awesome.

**Comment by h6ah4i** [comment]
Hi. Unfortunately this library does not support such behavior and I do not have any ideas how to achiave that :(

**Comment by ArunPandiyan** [comment]
Anyway Thanks h6ah4i(seriously no name to thank) ;)
