### ISSUE TITLE
Can I drag item in just a specific location??

### ISSUE THREAD

**Issue by lkevin029** [h6ah4i/android-advancedrecyclerview#223]
Can I drag item in just a specific location?? 
example 
i have 
1 2 3 4 5 
6

1 can only drag in 6 and will not animate while dragging like 2 1 3 4 5  . . .      2 3 4 5 1 

just 
2 3 4 5 6
1

is this possible ?

**Comment by h6ah4i** [comment]
Hi. Sorry this library does not support such behavior. I guess implementing such behavior with RecyclerView is difficult :(

**Comment by lkevin029** [comment]
there is a library this scenario is possible but its impelemented in  IOS  Swift not in android >.<
 https://github.com/ra1028/RAReorderableLayout
this method do the work
optional func collectionView(collectionView: UICollectionView, atIndexPath: NSIndexPath, canMoveToIndexPath: NSIndexPath) -> Bool

**Comment by h6ah4i** [comment]
Thanks for your info, it helps me a lot :) I found out how to achieve the same behavior. I am going to update the develop branch after I go back to home today.

---
MEMO:

Look at the line 1394 of the RecyclerViewDragDropManager. If the `checkInRange()` method returns `false`, swapping will not be occurred. I will add a little bit modification to make library users can implement more flexible control whether the dragging item can drop to the specified position.

https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.8.7/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/draggable/RecyclerViewDragDropManager.java#L1394

**Comment by lkevin029** [comment]
Thx a lot

**Comment by h6ah4i** [comment]
Hi @lkevin029, I have just pushed a new branch which includes new `onCheckCanDrop()` method.
https://github.com/h6ah4i/android-advancedrecyclerview/tree/feature/support_check_can_drop_callback

#### How to use the new feature

1. Call `RecyclerViewDragDropManager.setCheckCanDropEnabled(true)`

  ```java
  dragMgr.setCheckCanDropEnabled(true);
  ```
  :point_right:  [`Actual usage in demo app`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/feature/support_check_can_drop_callback/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_d_check_can_drop/DraggableCheckCanDropExampleFragment.java#L68)
2. Implement `onCheckCanDrop()` on your adapter

  ```java
  @Override
  public boolean onCheckCanDrop(int draggingPosition, int dropPosition) {
      return (draggingPosition % 2) == (dropPosition % 2);
  }
  ```
  :point_right:  [`Actual usage in demo app`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/feature/support_check_can_drop_callback/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_d_check_can_drop/DraggableCheckCanDropExampleItemAdapter.java#L151)

---

You can try the latest library through JitPack:

```gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.h6ah4i:android-advancedrecyclerview:7acb96ca855022bbe32db03c410166744ce0ecd5'
}
```

**Comment by lkevin029** [comment]
thank you for this  👍
