### ISSUE TITLE
overscrolling effect

### ISSUE THREAD

**Issue by mars3142** [h6ah4i/android-advancedrecyclerview#23]
The overscroll effect is shown too early. The item is not at the top at this moment.

![draggable_recyclerview](https://cloud.githubusercontent.com/assets/220423/7155386/972dd7d6-e35e-11e4-920f-eb3d0b081e2c.png)

**Comment by h6ah4i** [comment]
Thanks for the report. I will tweak the threshold whether to draw edge effects.

**Comment by h6ah4i** [comment]
Fixed in 0.7.0.
