### ISSUE TITLE
Not allow drag action on specific item

### ISSUE THREAD

**Issue by pqtuan86** [h6ah4i/android-advancedrecyclerview#230]
Hi,
Is there a way to lock (not allow to drag) a specific item on grid layout? That specific item just receive the onclick event.

Any guidance will be appreciated!
Thanks a lot!

**Comment by h6ah4i** [comment]
@pqtuan86 Hi. The `onCheckCanStartDrag()` can be used for the purpose. Return `false` if the specified position item is locked.

---

Actual usage in the demo app:

- https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.8.7/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_d_with_section/DraggableWithSectionExampleAdapter.java#L168

```java
    @Override
    public boolean onCheckCanStartDrag(MyViewHolder holder, int position, int x, int y) {
        // x, y --- relative from the itemView's top-left

        // return false if the item is a section header
        if (holder.getItemViewType() != ITEM_VIEW_TYPE_SECTION_ITEM) {
            return false;
        }

        final View containerView = holder.mContainer;
        final View dragHandleView = holder.mDragHandle;

        final int offsetX = containerView.getLeft() + (int) (ViewCompat.getTranslationX(containerView) + 0.5f);
        final int offsetY = containerView.getTop() + (int) (ViewCompat.getTranslationY(containerView) + 0.5f);

        return ViewUtils.hitTest(dragHandleView, x - offsetX, y - offsetY);
    }
```

**Comment by pqtuan86** [comment]
Thanks, it's working now!
