### ISSUE TITLE
NotifyDataSetChanged caused recycleview to blink

### ISSUE THREAD

**Issue by taingmeng** [h6ah4i/android-advancedrecyclerview#232]
When there are items in recycleview, and I pull to refresh to get updated items from server, pass them into adapter and call notifyDataSetChanged in the adapter. It caused the recycleview to blink. The adapter here is the original adapter, not the wrapped adapter. Am I updating wrong adapter or is there any addition all steps to avoid the blink?

**Comment by h6ah4i** [comment]
Hi. Maybe, `setSupportsChangeAnimations(false)` will solve the problem.

```java
((DefaultItemAnimator) recyclerView.getItemAnimator()).setSupportsChangeAnimations(false);
```
ref.) [`SimpleItemAnimator.html#setSupportsChangeAnimations(boolean)`](http://developer.android.com/reference/android/support/v7/widget/SimpleItemAnimator.html#setSupportsChangeAnimations(boolean))

Or if you want to finish all other animations (move, add or delete) immediately, try the following code.

```java
recyclerView.getItemAnimator().endAnimations();
```

**Comment by taingmeng** [comment]
Thank you for your swift reply. I have found the reason. The fault is on my side where I always return different long id in getItemId(int position) in the adapter when I do refresh.

**Comment by h6ah4i** [comment]
Yes, that is the correct solution. Using not consisted ID value causes such unwanted item animations.

**Comment by bhargavbvs** [comment]
Hi, I implemented the moveitem in draggable grid layout and this causes for bad animation. It is going back to the same position and after moving and then the data changes. How to solve this!!

**Comment by taingmeng** [comment]
Did you override getItemId correctly? If you have duplicate ids, your app might crash or views will return back to the same position.
```
@Override
public long getItemId(int position) {
        //return unique id for each view
 }
```

**Comment by bhargavbvs** [comment]
@Override
    public long getItemId(int position) {
        return position;
    }

Yes, I have done that! I have implemented my own moveItem as he uses the AbstractDataProvider

private void moveItem(int fromPosition, int toPosition){
        final String item = strings.remove(fromPosition);
        strings.add(toPosition, item);
    }

**Comment by taingmeng** [comment]
By returning the position as id, I don't think it will work as you expected. Usually I return the unique attribute of the item at that position, for example, 
```
@Override
public long getItemId(int position) {
    return items.get(position).getId();
}
```
In your case, if each string in strings is unique, you can try: 
```
@Override
public long getItemId(int position) {
    return strings.get(position).hashCode();
}
```
It is not a fool-proof solution, but it should work.

**Comment by bhargavbvs** [comment]
Cool, struggling to find what went wrong. Thanks for your time man! This should be properly documented in the library that the unique attribute should be given.

**Comment by bhargavbvs** [comment]
I now has the same issue of blinking recyclerview after moving items even though the ids are unique.

**Comment by taingmeng** [comment]
If you encounter blinking as I did, make sure the id you return is unique and does not change when you move view or at any point of time.

If you use strings.get(position).hashCode() as I suggested, and any string in strings is changed, it might cause blinking.
