### ISSUE TITLE
Expand problem

### ISSUE THREAD

**Issue by k1589645** [h6ah4i/android-advancedrecyclerview#233]
HI Can I Expand different child from different group?
     OR Can I lock specific item (cannot to expand) ?

Thank for your help~

**Comment by h6ah4i** [comment]
Hi :)

> Can I lock specific item (cannot to expand) ?

If you don't want to expand/collapse a group when touching the item, please implement the `onCheckCanExpandOrCollapseGroup()` method always returns false.



> Can I Expand different child from different group?

Set on click listener to each item views and call the `expandGroup()` method on clicked.

```java
RecyclerViewExpandableItemManager.expandGroup(int groupPosition)
RecyclerViewExpandableItemManager.collapseGroup(int groupPosition)
```

---

Related issues
- [Force expand/colapse #11](https://github.com/h6ah4i/android-advancedrecyclerview/issues/11)

**Comment by k1589645** [comment]
Thanks , it work for me
> Hi :)
> 
> Can I lock specific item (cannot to expand) ?
> If you don't want to expand/collapse a group when touching the item, please implement the onCheckCanExpandOrCollapseGroup() method always returns false.

 Sorry
I still no idea for the usefulness and usage of 
```
RecyclerViewExpandableItemManager.expandGroup(int groupPosition)
RecyclerViewExpandableItemManager.collapseGroup(int groupPosition)
```

In my project,
```
@Override
        public void onClick(View v) {
            if (mItemClickListener != null) {
                mItemClickListener.onItemClick(v, groupPosition);
            }
            RecyclerViewExpandableItemManager re = new RecyclerViewExpandableItemManager(null);
            Log.d("test", re.expandGroup(groupPosition)+"");
        }
```
how can i improve the code,
Thank you for your time

**Comment by h6ah4i** [comment]
@k1589645 Hi. Need to use the `RecyclerViewExpandableItemManager` instance which is created in your Activity or in Fragment. Please refer the following demo code. Thanks.

- https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.8.7/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_e_add_remove/AddRemoveExpandableExampleAdapter.java#L121

**Comment by k1589645** [comment]
It totally solve my problem.
Thank you for your share. It's a useful lib.
