### ISSUE TITLE
How can I catch the event when fromPosition == toPosition In draggable?

### ISSUE THREAD

**Issue by gunC** [h6ah4i/android-advancedrecyclerview#245]
I want to catch the event when fromPosition == toPosition In DraggableGrid.
DraggableItemAdapter:public void onMoveItem(int fromPosition, int toPosition) ;
How can I do?

**Comment by h6ah4i** [comment]
Hi. Please use [`OnItemDragEventListener.onItemDragFinished()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.9.0/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/draggable/RecyclerViewDragDropManager.java#L88) callback for the purpose.

```java
dragDropMgr.setOnItemDragEventListener(new RecyclerViewDragDropManager .OnItemDragEventListener() {
    @Override
    void onItemDragFinished(int fromPosition, int toPosition, boolean result) {
        ...
    }
    ...
});
```
