### ISSUE TITLE
can't restore view place when drag like fling

### ISSUE THREAD

**Issue by magicyoung6768** [h6ah4i/android-advancedrecyclerview#251]
When I start drag,I move finger very fast,just like fling.
Then the child view retain the wrong place

**Comment by h6ah4i** [comment]
Hi. Which type of layout manager do you use? I can see such issue with `GridLayoutManager` or `StaggeredGridLayoutManager`. If you are using`LinearLayoutManager`, could you upload a screen recorded video? Thanks.

**Comment by magicyoung6768** [comment]
Thanks.I solve the problem because I use `ObservableRecyclerView` and override `touchEvent`,but when I use `GridLayoutManager` or `StaggeredGridLayoutManager`, it recurrent
