### ISSUE TITLE
Question:[Expandable] How to modify the divider of groups

### ISSUE THREAD

**Issue by AhmadMuzakkir** [h6ah4i/android-advancedrecyclerview#258]
In the Sample app, in Expandable (Basic) page.

The group and child clearly have different dividers.

![screenshot_2016-06-03-13-01-20](https://cloud.githubusercontent.com/assets/10398517/15769280/2edba1fc-298c-11e6-9eb5-063c71ffef09.png)

The child has a horizontal line as divider.
I'm guessing, the group has a empty space as divider.

My question is how to modify the divider of group.
For example:
1. I want to use a different divider on groups only.
2. I want to increase the spacing between groups.

Thank you in advance for your helps.

**Comment by h6ah4i** [comment]
Hi. 

> 1. I want to use a different divider on groups only.
> 2. I want to increase the spacing between groups.
In the demo app, I use `android:marginTop` for making a spaces between group items. Increase it if you just want to change the spacing. If you want to use divider (not just a spacing), create your own custom `ItemDecoration`.

Thanks.

**Comment by AhmadMuzakkir** [comment]
@h6ah4i Thanks a lot for your help and this awesome library.

Do you have any tips on how to differentiate between between Group view and Child view in the onDraw method ?

Right now I am doing it like this:
```
private void draw(Canvas c, RecyclerView parent, RecyclerView.State state) {
    final AbstractExpandableItemViewHolder childHolder = (AbstractExpandableItemViewHolder) parent.getChildViewHolder(child);
    if (childHolder instanceof ExpandableExampleAdapter.MyGroupViewHolder) {
        // Do stuffs
    }
}
```
