### ISSUE TITLE
Exapndable RV is populating twice ?

### ISSUE THREAD

**Issue by AruLNadhaN** [h6ah4i/android-advancedrecyclerview#263]
Hey,
I'm using a Expandable RV in my App. The problem is that there is another RV behind the original RV. 

Please take a look at the below image.
http://i.imgur.com/PB0jEfa.png

I don't know why the RV is being shown up twice?

**Comment by h6ah4i** [comment]
@AruLNadhaN Hi. Could you provide an example code/project which can produce the same issue? I need more info to give you some advices. Thanks.

**Comment by AruLNadhaN** [comment]
Please take a look at my gist here https://gist.github.com/AruLNadhaN/7d92e21f13c273ed199d2e17a6aac338

**Comment by h6ah4i** [comment]
Thanks. I am going to check them on this weekend.

**Comment by h6ah4i** [comment]
Hi. I downloaded your code and creared a simple app which uses all of your uploaded code. Unfortunately, it does not reproduce the same issue that you mentioned.


 How do you call the `populateRV()` method in your Activity. I guess `savedInstanceState == null` check is missing before invoking `populateRV()`, or called twice or more in your app. Thanks.

**Comment by AruLNadhaN** [comment]
It was called twice in the app!
