### ISSUE TITLE
Error:(43, 14) Failed to resolve: com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.9.1 

### ISSUE THREAD

**Issue by tobex9434** [h6ah4i/android-advancedrecyclerview#264]
I'm trying to use the library in a project and i'm getting this error. I do have jcenter() in my repositories.

**Comment by tobex9434** [comment]
i had to change my syntax from this:

repositories {
    jcenter()
}

to this: 

repositories {
    jcenter {
        url "http://jcenter.bintray.com/"
    }
}

**Comment by xiejinglan** [comment]
"compile 'com.android.support:recyclerview-v7:22.+'" try to add recyclerview support in your project ?

**Comment by tobex9434** [comment]
i already had that in my dependencies, my comm  comment above was d problem, thanks though
