### ISSUE TITLE
How do not draw SimpleListDividerDecorator when item is above a Section?

### ISSUE THREAD

**Issue by guidedways** [h6ah4i/android-advancedrecyclerview#265]
I'm using the ExpandableItemViewHolder example where I've got sections and then items underneath. I'm using 'SimpleListDividerDecorator' which works well, but I'd like it to not draw a separator when the next item below is an ExpandableItemViewHolder (i.e. a Group item). How can I do this?

**Comment by h6ah4i** [comment]
Hi. Adding a some `android:marginTop` to group items will work ([this technique is use in the demo app](https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.9.1/example/src/main/res/layout/list_group_item.xml#L23)).

If you need more flexible control of drawing dividers, make your own `ItemDecoration`.

Thanks.

**Comment by guidedways** [comment]
Thanks, ended up making my own
