### ISSUE TITLE
Item dropped on another item event?

### ISSUE THREAD

**Issue by Rexota** [h6ah4i/android-advancedrecyclerview#267]
I'm using this great library, thanks for your efforts. I want to implement [this kind of view ](http://i.utdstc.com/screen/android/thumb/uc-browser-mini-for-android-019.png). 

For example, when I drag an item over another item, it should create a folder. How can I capture that event? Because there is only `onMoveItem(from, to) `method.  What I want is create a custom method like `onItemDroppedOverItem(from, to)`.

I know this is a little complex, but would like to get an idea.

Thanks.

**Comment by h6ah4i** [comment]
Hi. Adding a method like `onItemDroppedOverItem(from, to)` and support creating a folder operation is possible, but is it what only you need?

I guess implementing home screen launcher like behaviors are very difficult, maybe it requires fully custom made layout manager or non-RecyclerView based custom views. In generally, home screen launcher provides very smart drag and drop operations with very sophisticated animations it cannot be achieved with normal RecyclerView with GridLayoutManger.

For instance, [Android's default launcher](https://android.googlesource.com/platform/packages/apps/Launcher3/) uses custom views and it does not use `RecyclerView` for main grid view (called [Workspace](https://android.googlesource.com/platform/packages/apps/Launcher3/+/master/src/com/android/launcher3/Workspace.java)).

**Comment by Rexota** [comment]
@h6ah4i, Thanks for your detailed response. I guess I'll implement what most launcher's do, as you said. Thanks again.
