### ISSUE TITLE
How to start dragging from the moment the user first touch the handle?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [h6ah4i/android-advancedrecyclerview#273]
Instead of long click or dragging the handle, is it posible to start the dragging or show the dragging effect, right on the first touch on the handle ?

**Comment by h6ah4i** [comment]
Thank you for the suggestion. I will try to implement it later.

**Comment by AndroidDeveloperLB** [comment]
Wow thank you.

**Comment by h6ah4i** [comment]
@AndroidDeveloperLB Hi. I have just created the `setInitiateOnTouch()` method. This method will be included in the next release. Thanks 😉 

```java
dragManager.setInitiateOnTouch(true);
```
---

Tip: try `develop` branch library via JitPack.

```gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.h6ah4i:android-advancedrecyclerview:f24c5ef15b32875f21a0997ebd4d99d0505c7d57'
}
```

**Comment by AndroidDeveloperLB** [comment]
Seems to work well, but what was the "transitive=true" in original one?

**Comment by h6ah4i** [comment]
@AndroidDeveloperLB 

> what was the "transitive=true" in original one?

I have added `@aar` artifact only notation to the original gradle setting. If the library has jar file type dependencies, specifying `transitive = true` is required. But maybe, this library will work without `@aar` or `transitive = true` for now.


http://stackoverflow.com/a/31753839

**Comment by AndroidDeveloperLB** [comment]
Well it works for,  at least.
