### ISSUE TITLE
list swipe back when notifydatasetchange called

### ISSUE THREAD

**Issue by shayan3985** [h6ah4i/android-advancedrecyclerview#274]
hi 
actually i need to update my whole list every 1 sec  ( cause my data update at this rate)
so i  implemented this functionality and its fine  .
the problem is 
when user swiped  or swiping the view and at this moment  notify Data Set Change method called

no matter of position of view  it swipe back and return to normal 

any idea what should i do to don't affecting  state of view on notify changes ??

**Comment by h6ah4i** [comment]
Hi. Unfortunately, there is no way to avoid such auto swipe cancellation on data set update during swiping for now. However, it might be possible to implement so I will give it a try tomorrow.

**Comment by shayan3985** [comment]
i appreciate your help 
actually yes i ve used `notifyDataSetChanged()` by now
but its  ok  i can use other method if they ll work i can manage that

**Comment by h6ah4i** [comment]
@skyfishjy Hi. I have just pushed an experimental feature branch which includes fix of the issue. Could you try it via JitPack? Thanks.

```gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.h6ah4i:android-advancedrecyclerview:dd72fdda74f27890b87837abe8916c20e5bf3ea7'
}
```

**Comment by shayan3985** [comment]
@h6ah4i  hi. i 've tested your branch and used `notifyItemChanged()` 
works very fine on swiping(when i still hold my tip) the view  nice job!

but it still swipe back  when the swipe is done (the time that e.g the button is revealed  and user need to click it but unfortuantly the view swiping back to normal )

plz notify me when u merge it with your main branch

very very thank you btw 
u saved my life so far :))

**Comment by h6ah4i** [comment]
@shayan3985 

> but it still swipe back when the swipe is done (the time that e.g the button is revealed and user need to click it but unfortuantly the view swiping back to normal )

Hi. This seems to be a different problem. Please check the following things in your code;

- Disable change animations

  ```java
  animator.setSupportsChangeAnimations(false);
  ```

- Handle pinned state properly in `onBindViewHolder`

  ```java
  @Override
  public void onBindViewHolder(MyViewHolder holder, int position) {
      ...
      // call setSwipeItemHorizontalSlideAmount() in onBindViewHolder()
      // ex.)
      holder.setSwipeItemHorizontalSlideAmount(item.isPinned() ? -0.5f : 0); 
  }
  ```

If the issue is still present, could you upload an example code which can reproduce the same issue? Thanks.

**Comment by shayan3985** [comment]
@h6ah4i 
hi 
that was my mistake on updating my data from database that reset my data 's pin status
 and i fixed that 
thanks a lot
