### ISSUE TITLE
Setonclick on child

### ISSUE THREAD

**Issue by cyber12341** [h6ah4i/android-advancedrecyclerview#275]
How to set onclick on child position

**Comment by h6ah4i** [comment]
Hi. Please check the implementation of "Expandable (Add/Remove items)" demo. 

- https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.9.1/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_e_add_remove/AddRemoveExpandableExampleAdapter.java#L174

You can use `setOnClickListener()` as usual. Then, obtain its group and child position like the following code snippet. Thanks.

```java
RecyclerViewExpandableItemManager expmgr = ...;

int flatPosition = vh.getAdapterPosition();
long packedPosition = expmgr.getExpandablePosition(flatPosition);
int groupPosition = RecyclerViewExpandableItemManager.getPackedPositionGroup(packedPosition);
int childPosition = RecyclerViewExpandableItemManager.getPackedPositionChild(packedPosition);
```
