### ISSUE TITLE
Onchangelistener

### ISSUE THREAD

**Issue by cyber12341** [h6ah4i/android-advancedrecyclerview#277]
i want to update data in the expandable, is it possible?
if it possible would you like to teach me ?

**Comment by h6ah4i** [comment]
Hi.Maybe, the following method is wha yoy are looking for.

-  [RecyclerViewExpandableItemManager.notifyChildItemChanged(int groupPosition, int childPosition)](https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.9.1/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L617)

This method can be used the same as [`notifyItemChanged()`](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyItemChanged(int)) for expandable list. Thanks.

**Comment by cyber12341** [comment]
i think what i want is to re-add all of the value in the expandable list

**Comment by h6ah4i** [comment]
Okay, I got it.  Calling [notifyDataSetChanged()](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyItemChanged(int)) will work in that situation.

**Comment by cyber12341** [comment]
and i want to about the child group in minimalist expandable, i cant see the clicked effect when i already make it? thanks alot

**Comment by h6ah4i** [comment]
@cyber12341 Hi. Thanks for pointing it out. Adding the following line solves the ripple effect problem.

```java
((SimpleItemAnimator) recyclerView.getItemAnimator()).setSupportsChangeAnimations(false);
```
