### ISSUE TITLE
setSpanSizeLookup while dragging but not drop yet.

### ISSUE THREAD

**Issue by trieulh-ict** [h6ah4i/android-advancedrecyclerview#278]
HI,
I'm using GridLayoutManager to do drag n' drop. The problem here is that while I'm dragging item A over item B which's next to, and when the item B is pushed out, it still uses SpanSize of item A, not resize.

My question is that how I can update SpanSize of item B when it is pushed to new place while I'm dragging (not drop yet).

Sr for my bad English.

**Comment by h6ah4i** [comment]
@trieulh-ict Unfortunately, there is no way to handle that problem for now. I will try to improve the behavior on this weekend. Thanks.

**Comment by h6ah4i** [comment]
I have fixed this issue, and the fix will be included to the next release 😄 
![](https://cloud.githubusercontent.com/assets/2552365/16544959/4562e2f2-4154-11e6-91d1-822725c759ad.gif)

**Comment by h6ah4i** [comment]
@trieulh-ict Hi. I have just released v0.9.2 and it includes the fix of this issue.

**Comment by trieulh-ict** [comment]
@h6ah4i Thank you in advanced. Unfortunately my idea is reverse with your update. :( For example in your gif, when 0-A is dragged over 1-B, I want the size of every single items is unchanged as initialized (0-A still takes the whole width). is it possible ?

**Comment by lightglitch** [comment]
@h6ah4i Can you add the example on the gif to your demo app?

**Comment by h6ah4i** [comment]
@trieulh-ict Hi. I think that can be achieved by modifying your `SpanSizeLookup` implementation. Use something *stable* value instead of using `position` directory to determine span size. For instance, the following example code uses `id` to determine span side.

```patch
--- a/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_d_grid/DraggableGridExampleFragment.java
+++ b/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_d_grid/DraggableGridExampleFragment.java
@@ -70,7 +70,17 @@ public class DraggableGridExampleFragment extends Fragment {

         //noinspection ConstantConditions
         mRecyclerView = (RecyclerView) getView().findViewById(R.id.recycler_view);
-        mLayoutManager = new GridLayoutManager(getContext(), 3, GridLayoutManager.VERTICAL, false);
+        mLayoutManager = new GridLayoutManager(getContext(), 6, GridLayoutManager.VERTICAL, false);
+
+        ((GridLayoutManager) mLayoutManager).setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
+            int[] map = new int[]{6, 2,2,2, 1,1,1, 3, 3,3, 1,3,1,1 };
+            @Override
+            public int getSpanSize(int position) {
+                int index = (int) mWrappedAdapter.getItemId(position);
+               // int index = position;   // uncomment this line to restore the previous gif behavior
+                return map[index % map.length];
+            }
+        });

         // drag & drop manager
         mRecyclerViewDragDropManager = new RecyclerViewDragDropManager();
```


Here is the result gif.

![1](https://cloud.githubusercontent.com/assets/2552365/16768550/be7857e4-487f-11e6-91e8-00514ef51a25.gif)


However, sometime it does not work well. Flicker might be caused if layout has gaps, and sadly this annoying behavior is not able to be fixed.

![2](https://cloud.githubusercontent.com/assets/2552365/16768573/d385cbe4-487f-11e6-80c8-5060bfa0118d.gif)

**Comment by h6ah4i** [comment]
@lightglitch Hi. Please check my previous reply to this thread, I have put a patch on it. 

BTW, I am unwilling to add a new example. As you can see, the patch is very short and it does not use any features of this library, just setting a normal `SpanSizeLookup` and it is straightforward way of `RecyclerView`.

**Comment by lightglitch** [comment]
@h6ah4i Thx, would to possible to do something similar but for the StaggeredGridLayoutManager? I need different height sizes?

**Comment by lightglitch** [comment]
Basically I wanted to replicate this:

![](https://github.com/ra1028/RACollectionViewReorderableTripletLayout/raw/master/Assets/animation.gif)

**Comment by trieulh-ict** [comment]
@h6ah4i You're the beast. That's what I really want. 👍

**Comment by h6ah4i** [comment]
@lightgritch Unfortunately, that seems impossible to creare with stock layout managers. Need to create your own layout manager or use [TwoWayView](https://github.com/lucasr/twoway-view). Also this library won't support non standard layout managers, so use  [ItemTouchHelper](https://developer.android.com/reference/android/support/v7/widget/helper/ItemTouchHelper.html) instead or implement drag action from scratch.

**Comment by lightglitch** [comment]
@h6ah4i thx for the info
