### ISSUE TITLE
Listener to handle click/touch on group item

### ISSUE THREAD

**Issue by simopete** [h6ah4i/android-advancedrecyclerview#28]
Hi there, 
I would like to do some changes with the group item's view when click occured on it. 
Because your `RecyclerViewExpandableItemManager` handle the touch on the `RecyclerView` I can't attach `OnClickListener` to my `View`.
I recommend you do a listener which can set up for the manager class with `View` and `MotionEvent` and call it before you return in your `onInterceptTouchEvent` method.

**Comment by h6ah4i** [comment]
Hi. Sorry for the poor documentation :disappointed:

Try to implement the `onCheckCanExpandOrCollapseGroup()` method always return `false`. It enables `OnClickListener` work as you expected.

Related issue: [#11 Force expand/colapse](https://github.com/h6ah4i/android-advancedrecyclerview/issues/11)

**Comment by simopete** [comment]
Thanks your answer. 
I can do it what I wanted with your suggestion. 
Thank you for your work! :+1:
