### ISSUE TITLE
How to save and restore button position RecyclerView

### ISSUE THREAD

**Issue by peppe130** [h6ah4i/android-advancedrecyclerview#280]
Hi,

How can I add items to an Array to a specific index which is saved into SharedPreferences? So I can restore the buttons order when the App is launched. Thanks!

**Comment by h6ah4i** [comment]
Hi. It seems that this question is not related to Advanced RecyclerView :confused: Just save the position where you want to insert items, then read it from `SharedPreferences` and reconstruct the `Array` contents before initializing a `RecyclerView`.
