### ISSUE TITLE
Swipe out animation does not seem to be executed.

### ISSUE THREAD

**Issue by zeroarst** [h6ah4i/android-advancedrecyclerview#285]
In the demo app (demo_s_button), when swipe left, I see the container does not smoothly move to left, instead, it just jumps to the given amount (-0.5f). 
The closed swipe animation is running well. When swipe to right I can see it smoothly move to right.

**Comment by h6ah4i** [comment]
Hi. Thanks for the report. I will improve the behavior in the next release.

**Comment by h6ah4i** [comment]
Hi. I have fixed this issue in v0.9.3.
