### ISSUE TITLE
Is it possible to give swipe amount in dip or pixel instead of percentage?

### ISSUE THREAD

**Issue by zeroarst** [h6ah4i/android-advancedrecyclerview#286]
I have a button in the back that has fixed width. 
![2016-07-22 11_01_30-5554_nexus_s_api_23](https://cloud.githubusercontent.com/assets/1834837/17043638/d1a1b5d0-4ffb-11e6-94e2-cdb70efc6f02.png)

However, in the lib it seems to accept percentage only.
These code are from demo.
```
// set swiping properties
holder.setMaxLeftSwipeAmount(-0.5f); 
holder.setMaxRightSwipeAmount(0);
holder.setSwipeItemHorizontalSlideAmount(mPinnedStatus[position] ? -0.2f : 0);
```
It would be good if we can also specify fixed value such as 50dp...etc.

**Comment by h6ah4i** [comment]
Hi. Thanks for your suggestion. I will try to implement it in the next release.

**Comment by h6ah4i** [comment]
@zeroarst Hi. I have added the following new methods in v0.9.3 and it can configure the item to handle swipe amount in fixed value(pixels).

- `void SwipebleItemViewHolder.setProportionalSwipeAmountModeEnabled(boolean enabled)`
- `boolean SwipebleItemViewHolder.isProportionalSwipeAmountModeEnabled()`

#### Usage:

Call `setProportionalSwipeAmountModeEnabled(false)` in `onBindViewHolder()`.

```java
    @Override
    public void onBindViewHolder(MyViewHolder holder, int position) {
        ...

        float density = holder.itemView.getResources().getDisplayMetrics().density;
        float pinnedDistance = (density * 100); // 100 dp

        holder.setProportionalSwipeAmountModeEnabled(false); // disable proportional amount mode
        holder.setMaxLeftSwipeAmount(-pinnedDistance);  // specify amount in pixels
        holder.setMaxRightSwipeAmount(0);
        holder.setSwipeItemHorizontalSlideAmount(item.isPinned() ? -pinnedDistance: 0);

        ...
    }
```
ref.) https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_s_button/SwipeableWithButtonExampleAdapter.java#L165
