### ISSUE TITLE
Images are loading slowly

### ISSUE THREAD

**Issue by sandeshnaroju** [h6ah4i/android-advancedrecyclerview#291]
@h6ah4i I am using this Library for Group and child views. Problem is whenever I click on Group, images(child views) are displaying few seconds after I click. What I understood is, first it is loading all the child views and displaying. Any solution for this? I am using Glide to load images from the sdcard.

**Comment by h6ah4i** [comment]
Thank you for the report. I will take it a look.

**Comment by sandeshnaroju** [comment]
@h6ah4i  Did you find  it? UI is freezing. When I click on Group, it is taking lot of time to show up the child items so the UI is freezing till all the images are loaded.It is happening when Images are childviews.Is it possible to showup the view first? and then I can load images in the view in thread.

**Comment by h6ah4i** [comment]
@sandeshnaroju Hi. That seems strange. Glide loads image asynchronously by default and it trys not to block UI thread too long. 


- How many child items are displayed on the screen at once?
  - 👉  Showing too much images causes UI performance issue.
- Do you resize images to appropreate resolution?
  - 👉  Too large image takes HUGE memory and HUGE resizing cost.
- Do you use  `wrap_content` to `ImageView`?
  - 👉  It needs more calculation on layout process.
- Do you use `wrap_content` to itemView and `RecyclerView.setHasFixedSize(false)`?
  - 👉  It needs more calculation on layout process.

I have modified the "minimal expandable" demo app to show pictures using Glide, but I have not able to reproduce the critical performance problem though 😥

**Comment by sandeshnaroju** [comment]
I have tried you suggested. But did not work. As the number of images(childviews) are inreasing, the time to load is also increasing. I figured that the onBindChildViewHolder is getting called for all the items first as soon as the Group is clicked. So it is loading all items first. After it loads it is displaying all at once. this is where the actual problem AFAIK. Is it by design?

**Comment by h6ah4i** [comment]
> I figured that the onBindChildViewHolder is getting called for all the items first as soon as the Group is clicked. So it is loading all items first. After it loads it is displaying all at once. this is where the actual problem AFAIK. Is it by design?

Yes, that behavior is by design of RecyclerView (maybe LinearLayoutManager). If you are using `wrap_content` instead of using fixed height to each items, `onBindViewHolder()` will be called to every inserted items in order to measure all their height.

> I have tried you suggested. But did not work.

Really? I confirmed that `onBindChildViewHolder()` is called for only displayed items when using fixed height items. I recommend to use both `RecyclerView.setHasFixedSize(true)` and *fixed height* items like the following. 

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="300dp">  <!-- do not use wrap_content here for performance reason! -->

    <ImageView
        android:id="@+id/image1"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

</FrameLayout>
```

**Comment by sandeshnaroju** [comment]
Thank you. It worked. I was Instantiating new Database class  for everyitem. it is taking time to load from database. the reason is i am querying database in onBindChildViewHolder. I removed it. It is fine now. Thank you for your help.
