### ISSUE TITLE
Increase the size of draggable image

### ISSUE THREAD

**Issue by sprejjs** [h6ah4i/android-advancedrecyclerview#292]
Hi There,

I'm loving your library so far! It does almost everything I want it to, one last thing I cannot figure out how to implement is increasing the size of the draggable item.

Here is my current implementation:

<img width="567" alt="screen shot 2016-08-03 at 5 16 54 pm" src="https://cloud.githubusercontent.com/assets/4711044/17354612/2544f836-599e-11e6-8c8a-0899777b962b.png">

And here is what I am trying to achieve:

<img width="487" alt="screen shot 2016-08-03 at 5 18 00 pm" src="https://cloud.githubusercontent.com/assets/4711044/17354623/4be00b84-599e-11e6-83cc-3eb8308cb35d.png">

Is there a way to achieve what I want with your library? I have spent the last 3 days reading through the code, but I can't seems to be able to figure it out.

**Comment by h6ah4i** [comment]
Hi. That feature is not present for now, so I will implement it in next release. Thanks for a good suggestion!

**Comment by h6ah4i** [comment]
@sprejjs Hi. I added a new feature to configure the appearance of the dragging item. Could you try the latest develop branch code via JitPack. Thanks!

#### Usage: (Scale 1.5x dragging item with animation)

```java
mRecyclerViewDragDropManager.setDragStartItemAnimationDuration(250);
mRecyclerViewDragDropManager.setDraggingItemScale(1.5f);

// this new ItemAnimator is required to make item drop animation work properly
mRecyclerView.setItemAnimator(new DraggableItemAnimator());
```

#### Gradle:

```gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.h6ah4i:android-advancedrecyclerview:c253ef247079973b1e42549c94e77f8bd831fd3f'
}
```


#### All newly added methods:

- `void setDraggingItemScale(float scale)`
- `float getDraggingItemScale()`
- `void setDraggingItemRotation(float rotation)`
- `float getDraggingItemRotation()`
- `void setDraggingItemAlpha(float alpha)`
- `float getDraggingItemAlpha()`
- `void setDragStartItemAnimationDuration(int duration)`
- `int getDragStartItemAnimationDuration()`
- `void setDragStartItemScaleAnimationInterpolator(Interpolator interpolator)`
- `void setDragStartItemRotationAnimationInterpolator(Interpolator interpolator)`
- `void setDragStartItemAlphaAnimationInterpolator(Interpolator interpolator)`

**Comment by h6ah4i** [comment]
![New drag and drop demo](https://cloud.githubusercontent.com/assets/2552365/17647748/5b95ebf8-623a-11e6-8e34-eb2de5d2651b.gif)

**Comment by sprejjs** [comment]
This is fantastic. Thank you very much!
