### ISSUE TITLE
Prepend instead of append

### ISSUE THREAD

**Issue by Flo354** [h6ah4i/android-advancedrecyclerview#296]
Hi,

I would like to prepend an element in a list instead of appending it. Is it possible ?

Thanks,

**Comment by h6ah4i** [comment]
Hi. Use [`RecyclerView.Adapter.notifyItemInserted(int position)`](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyItemInserted(int)) after added an item.

**Comment by Flo354** [comment]
Hi.

Thanks for your answer. I already use notifyItemInserted, but the problem is that the element appear at the end of the list. I want that the element appear in top of list.

**Comment by Flo354** [comment]
Ok, I found the solution. In the dataProvider, instead of using mData.add(element) in the LinkedList, I use mData.add(0, element). And notifyItemInserted(0);

Thanks
