### ISSUE TITLE
notifyDataSetChanged doesn't work in expandable recyclerview

### ISSUE THREAD

**Issue by rorschach** [h6ah4i/android-advancedrecyclerview#297]
I have a adapter extends AbstractExpandableItemAdapter in fragment, and put List<Data> from outside, this data instance was only in adapter. I provide a public method in adapter to update data, but it doesn't work after data show in logcat

```
public class AdjustAdapter extends
        AbstractExpandableItemAdapter<AdjustAdapter.DepartmentHolder, AdjustAdapter.MemberHolder> {

    private static final String TAG = "OkHttp";

    private WeakReference<Fragment> mReference;
    private List<AllScoreByDepartment> mList;
    private LayoutInflater mInflater;

    public AdjustAdapter(WeakReference<Fragment> reference) {
        mReference = reference;
        mList = new ArrayList<>();
        mInflater = LayoutInflater.from(mReference.get().getContext());
    }

    @Override public int getGroupCount() {
        return mList == null ? 0 : mList.size();
    }

    @Override public int getChildCount(int groupPosition) {
        List<Member> member = mList.get(groupPosition).getMembers();
        return member == null ? 0 : member.size();
    }

    @Override public long getGroupId(int groupPosition) {
        return mList.get(groupPosition).getId();
    }

    @Override public long getChildId(int groupPosition, int childPosition) {
        return mList.get(groupPosition).getMembers().get(childPosition).getId();
    }

    //...

    public void update(@NonNull List<AllScoreByDepartment> list) {
        mList.clear();
        mList.addAll(list);
        notifyDataSetChanged();//dosen't work
        Log.i(TAG, "update: " + mList);
    }
}
```

**Comment by rorschach** [comment]
I'm update my code like below, but it's doesn't work too

in fragment
```
    private AdjustAdapter mAdapter;
    private RecyclerView.Adapter mWrappedAdapter;
    private RecyclerViewExpandableItemManager mExpandableItemManager;

    WeakReference<Fragment> reference = new WeakReference<Fragment>(this);

    mExpandableItemManager = new RecyclerViewExpandableItemManager(null);

    mAdapter = new AdjustAdapter(reference, mExpandableItemManager);

    mWrappedAdapter = mExpandableItemManager.createWrappedAdapter(mAdapter);

    mRecyclerView.setHasFixedSize(true);
    mRecyclerView.setLayoutManager(layoutManager);
    mRecyclerView.setAdapter(mWrappedAdapter);

    mExpandableItemManager.attachRecyclerView(mRecyclerView);
```

in adapter 
```
    private WeakReference<Fragment> mReference;
    private RecyclerViewExpandableItemManager mItemManager;
    private List<AllScoreByDepartment> mList;
    private LayoutInflater mInflater;

    public AdjustAdapter(WeakReference<Fragment> reference,
            RecyclerViewExpandableItemManager itemManager) {
        mReference = reference;
        mItemManager = itemManager;
        mList = new ArrayList<>();
        mInflater = LayoutInflater.from(mReference.get().getContext());
        setHasStableIds(true);
    }

    public void update(@NonNull List<AllScoreByDepartment> list) {
        mList.clear();
        mList.addAll(list);
        mItemManager.notifyGroupItemRangeRemoved(0, mList.size());
        Log.i(TAG, "update: " + mList);
    }
```

**Comment by h6ah4i** [comment]
@rorschach Hi. 

Try using the [`notifyGroupItemRangeInserted(int groupPositionStart, int itemCount, boolean expanded)`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.9.3/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L770) method and specify `true` for the third parameter.

Alternatively, if you want to set expanded state as default, the [`setDefaultGroupsExpandedState(boolean expanded)`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.9.3/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L770) method can be used for the purpose.

**Comment by rorschach** [comment]
@h6ah4i Hi, i'm sorry to ignore the third parameter, now it's works. but i want to let the adapter refresh it's data, not only insert, cause i want to reset the data as raw data by click a button, and then use `mItemManager.notifyGroupItemRangeInserted(0, mList.size())` throw `IndexOutOfBoundsException`, how to solve it? Thank you :D

**Comment by rorschach** [comment]
Finally set ` mItemManager.setDefaultGroupsExpandedState(true)` and use `notifyDataSetChanged` to replace `mItemManager.notifyGroupItemRangeInserted(0, mList.size(), true)`, and it all works, thank you very much!

**Comment by jahangirkabir** [comment]
IndexOutOfBoundsException: Invalid index 10, size is 9
ExpandableRecyclerAdapter.getGroupId(ExpandableRecyclerAdapter.kt:108)

Where is the issue ?
