### ISSUE TITLE
Enhancement to Swiping

### ISSUE THREAD

**Issue by kuffs** [h6ah4i/android-advancedrecyclerview#30]
I believe it would be more useful to swipe and reveal a predetermined View/ViewGroup rather than a drawable as I think most people implementing this functionality would want to have buttons with click handlers etc displayed after swiping. (See example in the ReadMe image at https://github.com/47deg/android-swipelistview)

I would also prefer a pinned item to leave a small part of itself (or a dedicated grabhandle view) showing to indicate it can be dragged back into view.

Another point would be when an item is pinned, I attempted to swipe it back to unpin it which actually triggered the "swipe to delete" action after causing the pinned item to instantly reappear back in its default location.

Apart from those points, I think this is the most slick Recyclerview extension library I have seen to date.

**Comment by h6ah4i** [comment]
Hi. Thanks for your advice. I have just released v0.7.0 and it includes these improvements.

- Added a new demo "Button under swipeable view"
- Fix the behavior of dragging back a pinned item
