### ISSUE TITLE
Expand problem

### ISSUE THREAD

**Issue by soyuz7KOK** [h6ah4i/android-advancedrecyclerview#301]
Expanding is not working when using DataProvider with group items and child items.  However, group items not expanding.

Here is my current code
`public void onActivityCreated(Bundle savedInstanceState) {
        Log.v(LOGTAG,"onActivityCreated");
        super.onActivityCreated(savedInstanceState);

        mContent = (Content)getArguments().getSerializable(Constants.PARAM);

        mLayoutManager = new LinearLayoutManager(getContext());

        final Parcelable eimSavedState = (savedInstanceState != null) ? savedInstanceState.getParcelable(SAVED_STATE_EXPANDABLE_ITEM_MANAGER) : null;
        mRecyclerViewExpandableItemManager = new RecyclerViewExpandableItemManager(eimSavedState);
        mRecyclerViewExpandableItemManager.setOnGroupExpandListener(this);
        mRecyclerViewExpandableItemManager.setOnGroupCollapseListener(this);

        //adapter
        final ExpandableAudioDataAdapter myItemAdapter = new ExpandableAudioDataAdapter(getDataProvider());
        mWrappedAdapter = mRecyclerViewExpandableItemManager.createWrappedAdapter(myItemAdapter);       // wrap for expanding

        final GeneralItemAnimator animator = new RefactoredDefaultItemAnimator();

        // Change animations are enabled by default since support-v7-recyclerview v22.
        // Need to disable them when using animation indicator.
        animator.setSupportsChangeAnimations(false);

        binding.list.setLayoutManager(mLayoutManager);
        binding.list.setAdapter(mWrappedAdapter);  // requires *wrapped* adapter
        binding.list.setItemAnimator(animator);
        binding.list.setHasFixedSize(false);

    }`

**Comment by soyuz7KOK** [comment]
I've struggled with this problem all the day..

In my case,  mInternalUseOnItemTouchListener in RecyclerViewExpandableItemManager is created, but onInterceptTouchEvent method is never called when any group item is tapped.

What's wrong? Please help!

**Comment by h6ah4i** [comment]
@soyuz7KOK Hi. It seem that calling `attachRecyclerView()` method is missing.

```
mRecyclerViewExpandableItemManager.attachRecyclerView(mRecyclerView);
```

**Comment by soyuz7KOK** [comment]
i am so sorry for misunderstanding.
That was lack of documentation search. This was my fault. Thanks for reply and time. I really appreciate that.

Wish you have a great day.
