### ISSUE TITLE
[Expand Problem] : How to lock expanding of a specific group using onBindGroupViewHolder?

### ISSUE THREAD

**Issue by soyuz7KOK** [h6ah4i/android-advancedrecyclerview#302]
Hi,

i want to lock expanding of some specific groups (ie. if the group has only one child) and want to set the groups other click event listener in my custom ExpandableItemAdapter class.

i think i need to  implement in onBindGoupViewHolder, but how?

**Comment by h6ah4i** [comment]
@soyuz7KOK Hi. 

> i want to lock expanding of some specific groups

If you want to custom click event handling, make the `onCheckCanExpandOrCollapseGroup()` method always returns `false`, then set click listener in `onCreateGroupViewHolder()` (or in `onBindGroupViewHolder()`). In the click event handler, `collapseGroup()` / `expandGroup()` methods can be used to control the group's expanded state.

```java
@Override
public boolean onCheckCanExpandOrCollapseGroup(MyGroupViewHolder holder, int groupPosition, int x, int y, boolean expand) {
    return false;
}

@Override
public MyGroupViewHolder onCreateGroupViewHolder(ViewGroup parent, int viewType) {
    final LayoutInflater inflater = LayoutInflater.from(parent.getContext());
    final View v = inflater.inflate(..., parent, false);
    MyGroupViewHolder vh = new MyGroupViewHolder(v);
    vh.mSomeClickableView.setOnClickListener(this);
    return vh;
}

@Override
public void onClick(View v) {
    RecyclerView.ViewHolder vh = RecyclerViewAdapterUtils.getViewHolder(v);
    int flatPosition = vh.getAdapterPosition();

    if (flatPosition == RecyclerView.NO_POSITION) {
        return;
    }

    long expandablePosition = mExpandableItemManager.getExpandablePosition(flatPosition);
    int groupPosition = RecyclerViewExpandableItemManager.getPackedPositionGroup(expandablePosition);
    int childPosition = RecyclerViewExpandableItemManager.getPackedPositionChild(expandablePosition);

    // toggle expanded/collapsed
    if (mExpandableItemManager.isGroupExpanded(groupPosition)) {
        mExpandableItemManager.collapseGroup(groupPosition);
    } else {
        mExpandableItemManager.expandGroup(groupPosition);
    }
}
```

Please refer to the following adapter implementation in the demo app for actual usages;

- https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.9.3/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_e_add_remove/AddRemoveExpandableExampleAdapter.java

**Related issue**
- [Force expand/colapse #11](https://github.com/h6ah4i/android-advancedrecyclerview/issues/11)

**Comment by soyuz7KOK** [comment]
I could realize all i wanted!
Thanks for helpful advice:)
