### ISSUE TITLE
is there any way to implement expandable indicator (groupIndicator) [question] ?

### ISSUE THREAD

**Issue by LOG-TAG** [h6ah4i/android-advancedrecyclerview#31]
I'm looking for easy way to implement expandable indicator (groupIndicator) for this, atleast if we get the methods onexpanded, collapsed we can animate vectordrawables  on the header layout ! 

or custom options like this will be grateful 
android:groupIndicator="@drawable/settings_selector"    like expandablelistview !

**Comment by h6ah4i** [comment]
Hi. Maybe you can use `onBindGroupViewHolder()` method.

```java
@Override
public void onBindGroupViewHolder(MyGroupViewHolder holder, int groupPosition, int viewType) {
    if ((expandState & RecyclerViewExpandableItemManager.STATE_FLAG_IS_UPDATED) != 0) {
        if ((expandState & RecyclerViewExpandableItemManager.STATE_FLAG_IS_EXPANDED) != 0) {
            // onExpanded()
        } else {
            // onCollapsed()
        }
    }
}
```

**Comment by h6ah4i** [comment]
@LOG-TAG I have just updated the example code. Please see #35 for detail.
