### ISSUE TITLE
Compatibility with DiffUtil?

### ISSUE THREAD

**Issue by maksim88** [h6ah4i/android-advancedrecyclerview#313]
I have the advancedrecyclerview inside a view with a pull-to-refresh, so my list items can be refetched if the user wants to.
I currently just clear my items and readd them again when the response comes back.

Now Google released [DiffUtil](https://developer.android.com/reference/android/support/v7/util/DiffUtil.html) to make sure to update/add/remove the right items.
I tried adding it to my project but swiping stops working after the first pull-to-refresh.

Do you possibly intend to add compatiblity with `DiffUtil` or make a  custom implementation of diffing?

Thanks in advance!

**Comment by h6ah4i** [comment]
@maksim88 Hi. Sorry for the late reply 😞 

I believe `DiffUtil` can be used with the swipe feature of this library. Could you upload an example code which can reproduce the same issue? Thanks.

**Comment by maksim88** [comment]
You are right, the library works fine with `DiffUtil`.

I made a small sample project that works fine which can be found here if you're interested: https://github.com/maksim88/AdvRecyclerAndDiffUtil

The problem was that we did not override `getChangePayload()` and `onBindViewHolder()` correctly.
Thanks for your reply!

(and i'll close the ticket 😄)
