### ISSUE TITLE
Q - disable swipe on group items

### ISSUE THREAD

**Issue by LinkOut** [h6ah4i/android-advancedrecyclerview#316]
Using Expandable & Draggable & Swiping without section headers, i want to disable swipe on the Group item and keep on child... not only disable what the swipe do... i dont want the user to be able to swipe on group item... also on the child item i would like to let user only swipe a single way (right or left) not both...

Any suggestion for this?

Thanks

**Comment by h6ah4i** [comment]
Hi. That is easy. Modify your adapter's implementation like this:

```java
    @Override
    public int onGetGroupItemSwipeReactionType(MyGroupViewHolder holder, int groupPosition, int x, int y) {
        return Swipeable.REACTION_CAN_NOT_SWIPE_BOTH_H;
    }

    @Override
    public int onGetChildItemSwipeReactionType(MyChildViewHolder holder, int groupPosition, int childPosition, int x, int y) {
        if (onCheckChildCanStartDrag(holder, groupPosition, childPosition, x, y)) {
            return Swipeable.REACTION_CAN_NOT_SWIPE_BOTH_H;
        }

        return Swipeable.REACTION_CAN_SWIPE_LEFT; // or RIGHT
    }
```

**Comment by LinkOut** [comment]
Perfect! Thanks a lot. Great job
