### ISSUE TITLE
Add items with Drag and Drop adapter

### ISSUE THREAD

**Issue by joaosardinha** [h6ah4i/android-advancedrecyclerview#317]
Hey, awesome library!

Is there a built-in way to add items to the drag and drop adapter?

Simply doing 
```
list.add(i, string);
mWrappedAdapter.notifyItemInserted(i);
```
doesn't do anything.

**Comment by h6ah4i** [comment]
Hi. Please change `mWrappedAdapter` to `mAdapter`. Wrapper adapters can automatically relay `notify*` events of the underlying adapter(s).

**Comment by joaosardinha** [comment]
Hi thanks for the reply.

That won't work either, may the problem be with the data provider? The one I'm using is the one in the drag and drop basic example.

**Comment by h6ah4i** [comment]
Maybe there is a trivial implementation bug in your adapter or data provider.

> The one I'm using is the one in the drag and drop basic example.

Okay, here is a code snippet to add item insertion functionality to the basic D&D demo. Could you compare with your adapter/data provider implementation? Thanks.

```java
class DraggableExampleItemAdapter {
    @Override
    public void onBindViewHolder(MyViewHolder holder, int position) {
        holder.mContainer.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                RecyclerView rv = RecyclerViewAdapterUtils.getParentRecyclerView(v);
                RecyclerView.ViewHolder vh = rv.findContainingViewHolder(v);
                int position = vh.getAdapterPosition();

                mProvider.addNewItem(position);
                notifyItemInserted(position);
            }
        });

       ...
    }
   ...
}
```

```java
public abstract class AbstractDataProvider {
    public void addNewItem(int position) {
    }
    ...
}
```

```java
public class ExampleDataProvider {
    @Override
    public void addNewItem(int position) {
        // XXX: Need to improve ID generation code, because using mData.size() won't
        // work properly if once `removeItem()` is called.
        mData.add(position, new ConcreteData(mData.size(), 0, "THIS IS ADDED ITEM", 0));
    }
}
```

**Comment by joaosardinha** [comment]
You saved me days with this library, I'd love to see a donations button in the README soon. 
:)
