### ISSUE TITLE
Incorrect default Animator animations of items after Drag and Drop items

### ISSUE THREAD

**Issue by megaswet** [h6ah4i/android-advancedrecyclerview#324]
Hello,

Thanks for library!

I think I found some bug. I am using your demo_d_on_longpress example as base.

Correct default animation of items:
1. Let's fill list with items so little MORE than screen height:
item 0
item 1
item 2
item 3
...
item 9
2. Scroll down list
3. Remove items from 4 to 9 (for example by tapping on toolbar button)
4. We can see that list should animate (all items 0..3 animated by default ItemAnimator from top to bottom for align them into screen).

Wrong animation of items:
1. same (fill items 0..9)
1.1. move item 1 -> 2 (for example) by drag and drop (no matter long press or draggable view)
2. same (scroll down)
3. same (remove items from 4..9)
4. We can see that animation of 1 and 2 items is wrong (with wrong delay) item 1 and item 2 animated not synchronized with other items 0 and 3 and little bit overlapped during animation.

**Comment by megaswet** [comment]
Also, if I don't use drag and drop by finger and simply using direct method `onMoveItem(int fromPosition, int toPosition)` with `fromPosition = 1` and `toPosition = 2` in code animation of items is correct.

So the problem only in processing Drag and Drop in Manager by finger.

**Comment by h6ah4i** [comment]
Thank you for pointing it out! I have not noticed this bug until you mentioned. I'll try to fix it on this weekend!

| DefaultItemAnimator | RefactoredDefaultItemAnimator (with reordered list) |
|---|---|
| ![DefaultItemAnimator](https://cloud.githubusercontent.com/assets/2552365/20611818/b3a4185a-b2f4-11e6-955a-71f4f3246953.gif) | ![RefactoredDefaultItemAnimator](https://cloud.githubusercontent.com/assets/2552365/20611817/b060f26c-b2f4-11e6-8e5d-c94fce668edb.gif) |

**Comment by h6ah4i** [comment]
This issue has been fixed in v0.10.1. Reopen this if the issue still present. Thanks!
