### ISSUE TITLE
Draggable + Swipeable not working

### ISSUE THREAD

**Issue by Nxt3** [h6ah4i/android-advancedrecyclerview#326]
I followed the demo app to the letter and still can't get this to work.

[Here is my Adapter class](https://gist.github.com/anonymous/ce3a6ccefd118bb9669d35c4b63f60a8)

[Here is the Fragment that holds the list](https://gist.github.com/anonymous/3c94636235fb37a497eb6453632869bd)

[Here is the list view](https://gist.github.com/anonymous/6ede5966ff992595065fd3df2412d661)

Any help would be appreciated. Swiping works--but dragging does absolutely nothing.

**Comment by h6ah4i** [comment]
Hi. I noticed that your ViewHolder class does not implments `SwipeableItemViewHolder`. Just change super class to `AbstractDraggableSwipeableItemViewHolder` or implement like the following;

```java
static class ViewHolder extends AbstractSwipeableItemViewHolder implements DraggableItemViewHolder, View.OnClickListener {

    ...

    private int mDragStateFlags;

    @Override
    public void setDragStateFlags(int flags) {
        mDragStateFlags = flags;
    }

    @Override
    public int getDragStateFlags() {
        return mDragStateFlags;
    }
}
```

**Comment by Nxt3** [comment]
Oops. Not sure how I missed that. Thank you! Amazing library.
