### ISSUE TITLE
recyclerview in ScrollView or ViewPager

### ISSUE THREAD

**Issue by NeverGivinUp** [h6ah4i/android-advancedrecyclerview#33]
Currently, if the RecyclerView is embedded in a ScrollView or ViewPager, there is a race condition with them on dragging/swiping. Sometimes it does drag/swipe, many times it does not. To the user, the app feels broken. I make heavy use of ScrollViews and ViewPagers, so this is an important issue for me.

For drag&drop or swipe to work well in a ScrollView or ViewPager, the touch listeners must call ```recyclerView.getParent().requestDisallowInterceptTouchEvent(true)```, on ``` MotionEvent.ACTION_DOWN```, although they cannot know yet, whether the touch is a drag/swipe or just a click. (And they might need to intercept touch events of their children, too.) Then, they must watch the following touch events. If the user moves outside the touchSlop then they must start animating a drag/swipe if they are set up to it or re-allow the parents to intercept events (and maybe resend the events they received so far?). If the touch moves up before it leaves the touchSlop they must consider it a click and act on it, if they are set up for it, or tell the RecyclerView's parents/child about it. I think this is possible only, if the there is only a single touch listener for the recycler view, that takes full responsibility, as otherwise there would again be a race condition between touch listeners.

Do you agree share my understanding? Can you imagine changing this library to make it ScrollView/ViewPager embeddable?

Thanks a lot!

**Comment by fedeamura** [comment]
Use long click to enable the drag sort.

**Comment by h6ah4i** [comment]
Maybe this issue is fixed in v0.8.0.

- Drag & Drop can start on long click
- Swipe can start on long click
- Added a demo `Swipeable with ViewPager`
