### ISSUE TITLE
"Cannot resolve symbol 'example'" when importing -import com.h6ah4i.android.example

### ISSUE THREAD

**Issue by devious33** [h6ah4i/android-advancedrecyclerview#341]
![image](https://cloud.githubusercontent.com/assets/21035935/22395258/052f7f92-e573-11e6-9de3-36fc33769c64.png)

I've already implented the compilation needed on build.gradle and i have the jcenter(); as well
![image](https://cloud.githubusercontent.com/assets/21035935/22395261/2f94df8e-e573-11e6-90bc-61ce931b53a3.png)

**Comment by h6ah4i** [comment]
Hi. Those classes are not provided as a library because they are just sample implementation. Check the repository and copy them to your project if you need.

**Comment by devious33** [comment]
Figured so. Thanks for the steadfast response!
