### ISSUE TITLE
Get View from groupPosition

### ISSUE THREAD

**Issue by Flo354** [h6ah4i/android-advancedrecyclerview#343]
Hi,

I am a little bit stuck. When I add a group, in my notifyGroupInserted method, I want to get the View from the group position.

`
mRecyclerView.findViewHolderForItemId(mWrappedAdapter.getItemId(groupPosition)) => null
mRecyclerView.findViewHolderForLayoutPosition(groupPosition) => null
mRecyclerView.findViewHolderForAdapterPosition(groupPosition) => null
`

How can I get the view ? 

Thanks,

**Comment by h6ah4i** [comment]
Hi. Try the one of the followings code snippets.

#### via Group Position
```java
// group position => packed position => flat position => view holder
long packedPosition = RecyclerViewExpandableItemManager.getPackedPositionForGroup(groupPosition);
int flatPosition = expandMgr.getFlatPosition(packedPosition);
recyclerView.findViewHolderForAdapterPosition(flatPosition);
```

#### via Group ID
```java
// group position => group id => combined id => view holder
long groupId = mExpandableAdapter.getItemId(groupPosition);
long combinedId = RecyclerViewExpandableItemManager.getCombinedGroupId(groupId);
recyclerView.findViewHolderForItemId(combinedId);
```

**Comment by Flo354** [comment]
It's weird, both ways, the view is null

Logcat: 

> 01-31 18:37:07.074 26187-26187/com.arcansecurity.arcanaccess D/myView: groupPosition: 0
01-31 18:37:07.074 26187-26187/com.arcansecurity.arcanaccess D/myView: expandablePosition: -4294967296
01-31 18:37:07.074 26187-26187/com.arcansecurity.arcanaccess D/myView: flatPosition: 0
01-31 18:37:07.074 26187-26187/com.arcansecurity.arcanaccess D/myView: view: null
--> added one element in the first group
01-31 18:37:17.914 26187-26187/com.arcansecurity.arcanaccess D/myView: groupPosition: 1
01-31 18:37:17.914 26187-26187/com.arcansecurity.arcanaccess D/myView: expandablePosition: -4294967295
01-31 18:37:17.914 26187-26187/com.arcansecurity.arcanaccess D/myView: flatPosition: 2
01-31 18:37:17.914 26187-26187/com.arcansecurity.arcanaccess D/myView: view: null

Here is my code: 

        
        mAdapter.notifyDataSetChanged();

        getActivity().findViewById(R.id.textHelpAddGroup).setVisibility(View.GONE);

        final long expandablePosition = RecyclerViewExpandableItemManager.getPackedPositionForGroup(groupPosition);
        final int flatPosition = mRecyclerViewExpandableItemManager.getFlatPosition(expandablePosition);

        Log.d("myView", "groupPosition: " + groupPosition);
        Log.d("myView", "expandablePosition: " + expandablePosition);
        Log.d("myView", "flatPosition: " + flatPosition);
        Log.d("myView", "view: " + mRecyclerView.findViewHolderForAdapterPosition(flatPosition));

        mRecyclerView.scrollToPosition(flatPosition);

**Comment by h6ah4i** [comment]
Okay, using `findViewHolderFor*` methods immediately after calling a `notify*` method may returns `null`. This behavior is by design of RecyclerView (*1). To avoid this limitation, use the `post()` method (or `Handler`) like the following code.

```
final groupPosition = ...;

mAdapter.notifyDataSetChanged();

mRecyclerView.post(new Runnable() {
    @Override
    public void run() {
        long expandablePosition = RecyclerViewExpandableItemManager.getPackedPositionForGroup(groupPosition);
        int flatPosition = mRecyclerViewExpandableItemManager.getFlatPosition(expandablePosition);
        if (flatPosition != RecyclerView.NO_POSITION) {
            mRecyclerView.scrollToPosition(flatPosition);
        }
    }
});
```

Also, `findViewHolderForAdapterPosition()` and `findViewHolderForLayoutPosition()` returns `null` if the specified item position is out of the screen.

---

(*1) [Positions in RecyclerView - RecyclerView | Android Developers](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html)

**Comment by Flo354** [comment]
Oh, it's a tricky one. I now can get the view ! 

Thanks,
