### ISSUE TITLE
Inconsistency detected when using ExpandableItemAdapter and DiffUtils

### ISSUE THREAD

**Issue by TrevorSStone** [h6ah4i/android-advancedrecyclerview#344]
I have been trying to use DiffUtils with my expandable adapter and it is almost working perfectly. 
I am running into a (hopefully!) final problem where if multiple actions occur in the list that have a single item delete mixed in, the state of the adapter gets corrupted and I get:

```Exception java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{8f29659 position=9 id=48200705881669643, oldPos=9, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}```

I believe I have tracked this down to what looks like an optimization in ExpandableRecyclerViewWrapperAdapter in onHandleWrappedAdapterItemRangeRemoved

If there is only a single item it tries to remove just that instance from the translator. This has issues because if we had multiple actions on the list (maybe an insert above and a delete below) the insert calls rebuildPositionTranslator which rebuilds from the current dataset. The translator's state is now set to the most up to date state of the data, so when we try and find the data at that position in the translator it no longer matches the incremental state that the remove is expecting at this time. I believe that removing the itemcount==1 optimization would fix this, but I wanted to hear your thoughts.

Thank you

**Comment by h6ah4i** [comment]
Hi. Thanks for a pointed question!

I think every `WrapperAdapter` (yes, including the expandable feature) is *ill-suited* for use with `DiffUtils`.

Because, all of them expects `notify*` methods called synchronously with data set changes. It means you need to call corresponding `notify*` methods each after modification (add/remove/move) occurs one by one.

The behavior of `dispatchUpdatesTo(Adapter)` method says that the expectation of `WrapperAdapter` will break with the method. The document advices to use `dispatchUpdatesTo(ListUpdateCallback)` instead for the situation.

> ### dispatchUpdatesTo
>
> void dispatchUpdatesTo (Adapter adapter)
> Dispatches the update events to the given adapter.
>
> For example, if you have an Adapter that is backed by a List, you can swap the list with the new one then call this method to dispatch all updates to the RecyclerView.
>  ```
>  List oldList = mAdapter.getData();
>  DiffResult result = DiffUtil.calculateDiff(new MyCallback(oldList, newList));
>  mAdapter.setData(newList);
>  result.dispatchUpdatesTo(mAdapter);
>  ```
> Note that the RecyclerView requires you to dispatch adapter updates immediately when you change the data (you cannot defer notify* calls). The usage above adheres to this rule because updates are sent to the adapter right after the backing data is changed, before RecyclerView tries to read it.
>
> **On the other hand, if you have another AdapterDataObserver that tries to process events synchronously, this may confuse that observer because the list is instantly moved to its final state while the adapter updates are dispatched later on, one by one. If you have such an AdapterDataObserver, you can use dispatchUpdatesTo(ListUpdateCallback) to handle each modification manually.**

ref.) https://developer.android.com/reference/android/support/v7/util/DiffUtil.DiffResult.html#dispatchUpdatesTo(android.support.v7.widget.RecyclerView.Adapter)


Okay, it seems we should use `dispatchUpdatesTo(ListUpdateCallback)`. However, I have not bring the `DiffUtils` support to the library yet. Here is the why I have not implemented them;

1. Its too complicated!
    - `WrapperAdapter` provides very flexible functionalities, but its implementation need to be tied strongly to underlying dataset/child adapters. Even worse, this class is a public class so I cannot guarantee its implementation compatible with DiffUtils operation.
2. `ListUpdateCallback` does not provide enough callbacks (at least for me)
    - I want two more callbacks like `onBatchUpdateStart()` and `onBatchUpdateFinished()`.
    - Without the two methods, I need to write like below;
    ```
    val diffResult = DiffUtil.calculateDiff(DiffCallback(old, new), true)
        adapter.items = items
        diffResult.dispatchUpdatesTo(adapter)
    mWrappedAdapter.startBatchUpdate(); // Notify all underlying wrapped adapters to start batch update, so we can optimize (skip unnecessary operations) for bulk update.
    diffResult.ListUpdateCallback(new ListUpdateCallback() {
       ...
    });
    mWrappedAdapter.finishBatchUpdate(); // Notify all underlying wrapped adapters to finish batch update, apply finalizing process for bulk update.
    ```
3. Using `notifyDataSetChange()` method is enough for most cases.
    - I have not benchmarked yet, but I think `notifyDataSetChange()` is enough for most of cases.

**Comment by TrevorSStone** [comment]
Thanks for the response!
From looking at the expandable adapter it appeared that each action was rebuilding the position translator each time. This is suboptimal, but I don't see why it would crash, or become out of state (other than the example I referenced). Are there other instances where state is being modified that I might be missing? I made the change I suggested and am still seeing a crash every so often so it can't be the only issue :(

For point 1. I understand and don't have a better response than "But I want it to work!". It seems so close to working for my use-case right now that I don't quite want to give up yet

2. I would be happy to write a wrapper that would add those two callbacks. I think the "startBatchUpdate()" and "finishBatchUpdate()" would be a bit harder. Do you have a way that you envision those working? I am still pretty new to looking at the internals of the library so, as I mentioned earlier, I am quite possibly missing a few of the pitfalls

3. We were using notifyDataSetChange previously (one of the main reasons I picked this lib over others!) but have been moving over to DiffUtils and have found both performance and also UX advantages to it (predictive animations are nice for our use case).

I would love to hear more of your thoughts on the subject.

**Comment by TrevorSStone** [comment]
So, good news, it appears the new crash I was seeing was unrelated and it appears stable after removing the item == 1 block. Am I totally shooting myself in the foot by doing this?
