### ISSUE TITLE
Scroll to a child in a group?

### ISSUE THREAD

**Issue by prefect4742** [h6ah4i/android-advancedrecyclerview#347]
How do I scroll so that a speficied groupPosition/childPosition is visible on-screen, with a margin so that the child is centered? I tried setting the totalHeight to childCount * childItemHeight, and margins to childPosition * childItemHeight, but the scrolling seems inverted.

The margin parameters are within the group or for the whole view?

**Comment by h6ah4i** [comment]
Hi. Maybe `scrollToGroupWithTotalChildrenHeight()` is not what you are expecting for. This method tries to scroll to the specified group item, not to a child item.

![scroll_to_group](https://cloud.githubusercontent.com/assets/2552365/22623159/a19123ec-eb93-11e6-8ebd-90a84c2890b3.png)

---

If you want to scroll to a child item, try the following code snippet. (but I haven't tested this, so let me know if it does not work.)

```java
int groupPosition = ...;
int childPosition = ...;
int childItemHeight = ...;

int recyclerViewHeight = recyclerView.getHeight();

int offset = -((recyclerViewHeight - childItemHeight) / 2);

long packedPosition = RecyclerViewExpandableItemManager.getPackedPositionForChild(groupPosition, childPosition);
int flatPosition = expMgr.getFlatPosition(packedPosition);

((LinearLayoutManager) recyclerView.getLayoutManager()).scrollToPositionWithOffset(flatPosition, offset);
```

**Comment by prefect4742** [comment]
Worked like a charm, except  I had to remove the "-" in the offset calculation. Thanks!
