### ISSUE TITLE
Do not apply ItemAnimator to GroupItems

### ISSUE THREAD

**Issue by chriswiesner** [h6ah4i/android-advancedrecyclerview#35]
Currently i have the issue that i want to rotate the expand/collapse indicator when a GroupItem is pressed.
This animation isn't shown because there is also the default Item animation.
Could you apply this animation just to the child items?

**Comment by h6ah4i** [comment]
Hi. Try to call `RecyclerView.ItemAnimator. setSupportsChangeAnimations(false)`. Also I have just updated the example code that demonstrates how to add expanded/collapsed status indicators to group items.

See also:
- https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ItemAnimator.html#setSupportsChangeAnimations(boolean)
