### ISSUE TITLE
Payloads disabled in expand/collapse group

### ISSUE THREAD

**Issue by rok5ek** [h6ah4i/android-advancedrecyclerview#350]
It would be of great help if we could add a payload in methods expandGroup and collapseGroup. As I can see the notifyItemChanged(flatPosition) is called, which means we cannot add a payload and do some custom animations more robustly.

**Comment by h6ah4i** [comment]
Hi. Thanks for a good suggestion. I will include this enhancement on next release!

**Comment by h6ah4i** [comment]
@rok5ek This feature has been merged and released as `v0.10.4` now.
