### ISSUE TITLE
Null pointer RecyclerViewDragDropManager.java:2222

### ISSUE THREAD

**Issue by polyak01** [h6ah4i/android-advancedrecyclerview#358]
Hi!) Its me again ✋ :D (https://github.com/h6ah4i/android-advancedrecyclerview/issues/351)

Faced with a new small problem. It happens also in your samples. 
module: DRAGGABLE (Grid Layout) (I didn't test other modules for this case)
Case: DURING dragging try to rotate device.  
Result: 
> java.lang.NullPointerException: Attempt to invoke virtual method void com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.cancelDrag(boolean)

> @Override
        public void handleMessage(Message msg) {
                switch (msg.what) {
....
case MSG_DEFERRED_CANCEL_DRAG:
// here 
                    mHolder.cancelDrag(true); 
                    ....
            }
        }`

**Comment by polyak01** [comment]
hot fix: 
if (mHolder != null) mHolder.cancelDrag(true);

**Comment by h6ah4i** [comment]
@polyak01 Thanks for the reporting issue! I found some severe faults in my code. I'll mention them on you PR.

**Comment by h6ah4i** [comment]
This feature has been merged and released as `v0.10.4` now.
