### ISSUE TITLE
utilizing setSwipeItemHorizontalSlideAmount with proportional mode disabled during initial layout doesn't work

### ISSUE THREAD

**Issue by frett** [h6ah4i/android-advancedrecyclerview#361]
When using a SwipeableItemAdapter and setting a swipeItemHorizontalSlideAmount with proportional mode disabled during initial item layout (width & height == 0 of the container), the container is laid out completely beyond the maxLeftSwipeAmount.

expected layout:
![screenshot_20170223-173422](https://cloud.githubusercontent.com/assets/47818/23282307/98ea1aaa-f9ee-11e6-99b7-1778e24363b7.png)

actual layout:
![screenshot_20170223-173430](https://cloud.githubusercontent.com/assets/47818/23282326/a28dc782-f9ee-11e6-9ee1-291c5a5bb1f4.png)

What I think is happening is that `slideToSpecifiedPositionInternal` within `ItemSlidingAnimator` is incorrectly checking the proportional flag and deferring the initial slide process. the deferred processing then doesn't take the proportional flag into account. I believe the correct fix is to change the if conditional here: https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/swipeable/ItemSlidingAnimator.java#L139 to testing `!proportional` instead of `proportional`.

**Comment by h6ah4i** [comment]
Thanks for the issue report! Definitely, the bug is caused by the incorrect branch condition that you pointed it out.

---

This bug was brought by the following my commit 😭
Support swipe amount handling in pixels. (#286)
- https://github.com/h6ah4i/android-advancedrecyclerview/commit/30cbc39897db4de970d017de6c31c4cb828dd1fd#diff-32f4b4fe94f138860685f0a37dd21440L139

**Comment by h6ah4i** [comment]
@frett Hi. I have just released `v0.10.4` that contains the fix of this bug.

**Comment by frett** [comment]
@h6ah4i thanks, I'll check it out when I'm back at work on Monday!
