### ISSUE TITLE
Expand item using a Button from within the adapter instead of using the itemView.

### ISSUE THREAD

**Issue by ghost** [h6ah4i/android-advancedrecyclerview#37]
I'd like to use a `Button` instead of the `itemView` as the trigger for expanding the group container.

I've read #11 but it requires an instance of `RecyclerViewExpandableItemManager`, which is declared outside of the adapter.

Is there any way to do so from within the adapter?

Your work is great @h6ah4i , thank you very much.

**Comment by mars3142** [comment]
@ghost I need the same, but I implement a workaround (listener) for this.

**Comment by thegeett** [comment]
I had same issue, what I did is just passed mRecyclerViewExpandableItemManager object in Adapter's constructor.
