### ISSUE TITLE
Strange bug only at Android 4.4.2 with drag

### ISSUE THREAD

**Issue by polyak01** [h6ah4i/android-advancedrecyclerview#370]
Hi!) Its me again :hand: :D

Strange bug only at Android 4.4.2. It does not appear on all devices, but sometimes bug happens. When I try to drag my item to the angle or end of the my RecyclerView - logic works fine, but piece of item hangs on the end. Immediately after position changing - everything works fine.

For more understanding, please, see [video](https://youtu.be/T2NNIwGetsg)

**Comment by h6ah4i** [comment]
Hmm... 🤔  It seems strange, `clipToChild` is not working properly only when dropping the items.

Try adding these properties to `RecyclerView` and its parent? If the issue still present, maybe we need to invalidate the parent view explicitly for workaround.

```xml
android:clipChildren="false"
android:clipToPadding="false"
```

**Comment by polyak01** [comment]
Fixed after setted false [here](https://github.com/h6ah4i/android-advancedrecyclerview/blob/4df3d7e3deddd002800124612aa9527771f80967/example/src/main/res/values/styles.xml#L25). 

But I don't know how it will work on [API 10](https://github.com/h6ah4i/android-advancedrecyclerview/blob/4df3d7e3deddd002800124612aa9527771f80967/example/src/main/res/values/styles.xml#L24) with false. But on Android 4.4+ work correct )

Thanks)
