### ISSUE TITLE
Swipe apartir de un onclick sobre el item

### ISSUE THREAD

**Issue by fabianmondragon** [h6ah4i/android-advancedrecyclerview#372]
Es posible lanzar el evento del swipe sin necesidad de hacer el swipe left, es decir al presionar sobre un boton que se encuentre en el layout del item?

**Comment by h6ah4i** [comment]
Hi. Currently there is no function that you want, so created a new method named `performFakeSwipe()`. This is still an experimental feature, so please add the following jitpack settings to your `build.gradle`.

```gradle
repositories {
    maven { url "https://jitpack.io" }
}
dependencies {
    compile 'com.github.h6ah4i:android-advancedrecyclerview:f4775fcb03fcda4bee8df4efdc7c47b4607d10e7'
}
```

#### Usage
```java
View v = ...;
ViewHolder vh = mRecyclerView.findContainingViewHolder(v);
int swipeResult = RecyclerViewSwipeManager.RESULT_SWIPED_LEFT;

mRecyclerViewSwipeManager.performFakeSwiping(vh, swipeResult);
```
