### ISSUE TITLE
View.OVER_SCROLL_NEVER not work when dragging

### ISSUE THREAD

**Issue by guochong** [h6ah4i/android-advancedrecyclerview#374]
already set View.OVER_SCROLL_NEVER flag ,bug when i dragging the item to the top edeg , recyclerView show the overscroll shadow too.

**Comment by kaeawc** [comment]
The culprit of this issue is `mEdgeEffectDecorator`. If this is simply not set when the recyclerview `mOrigOverScrollMode` is set to `View.OVER_SCROLL_NEVER`, then this issue can be resolved.

**Comment by h6ah4i** [comment]
Hi. I have just released v0.10.5 and it includes the fix of this issue 😉
