### ISSUE TITLE
onitemclicked sometimes triggered after long pressed

### ISSUE THREAD

**Issue by gewuxy** [h6ah4i/android-advancedrecyclerview#378]
I have use the draggable grid layout,and i find that onitemclicked sometimes triggered after long pressed, could anyone help?

**Comment by h6ah4i** [comment]
Hi. Thanks for reporting the issue! I have confirmed that this is a bug of Advanced RecyclerView. I have fixed it by the commit 2c0237a and this will be included to the next release. Until then, please use the fixed version via JitPack.

```gradle
repositories {
    maven { url "https://jitpack.io" }
}
dependencies {
    compile 'com.github.h6ah4i:android-advancedrecyclerview:2c0237a4d5f07f2cbbfa488961987780bd8c050d'
}
```
