### ISSUE TITLE
Issue with ExpandableDraggableSwipeable's child view with Background

### ISSUE THREAD

**Issue by kaas3031** [h6ah4i/android-advancedrecyclerview#383]
Hi, i am facing issue when i set background of Child view with ExpandableDraggableSwipeableExampleAdapter, in
 onBindChildViewHolder , i added below lines

if (groupPosition == 2) {
            holder.mTextView.setText(holder.mTextView.getText() + "-" + groupPosition);
            holder.mContainer.setBackgroundColor(Color.CYAN);
        }

so basically i added color for groupItem-2's child, it works fine if i navigate to tht screen and expand any of group except groupPosition2's but once i expand that group(display color for its child,and leave it expanded or even collapse) and then open any other group(expand) then it will copy its color to some of its child which i find weird , i am also attaching screen shot for the same, my expected behaviour is only give background to that particular group's children view not any other group's children 

VERSION_NAME=0.10.5
VERSION_CODE=27

![no issue](https://cloud.githubusercontent.com/assets/3184849/25165655/2d7fd886-24f5-11e7-9a21-b40c378f9e45.png)

![perfect_case](https://cloud.githubusercontent.com/assets/3184849/25165654/2d7df3a4-24f5-11e7-857a-54ebffe7ca87.png)

![issue_1](https://cloud.githubusercontent.com/assets/3184849/25165652/2d787bcc-24f5-11e7-936b-ab9a41ee7b0f.png)
![issue](https://cloud.githubusercontent.com/assets/3184849/25165653/2d7bd4f2-24f5-11e7-9327-7101bbfe0632.png)

**Comment by h6ah4i** [comment]
@kaas3031 Hi. Sorry for the late response 😞 

The behavior is just a nature of `RecyclerView`. `RecyclerView` reuses its item views automatically, so you need to reset background color for other child items.
