### ISSUE TITLE
How to adjustScrollPositionOnGroupExpanded in ComposedAdapter ?

### ISSUE THREAD

**Issue by LoveqLRC** [h6ah4i/android-advancedrecyclerview#390]
How to adjustScrollPositionOnGroupExpanded in ComposedAdapter ?

**Comment by h6ah4i** [comment]
@LoveqLRC Hi. Thanks for pinting it out the issue. Currently (= v0.10.6), the `scrollToGroup()` method does not work well with `ComposedAdapter`. I have added a new variant of the method which takes an additional "adapter path" parameter.

Please take a look at the [demo_issue_390](https://github.com/h6ah4i/android-advancedrecyclerview/blob/demo_issue_390/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_e_basic/ExpandableExampleFragment.java) branch code.


#### usage
```java
// initialization
mAdapter = new ExpandableExampleAdapter(getDataProvider());

mExpandableWrappedAdapter = mRecyclerViewExpandableItemManager.createWrappedAdapter(mAdapter);
mHeaderFooterAdapter1 = new DemoHeaderFooterAdapter(mExpandableWrappedAdapter);
mHeaderFooterAdapter2 = new DemoHeaderFooterAdapter(mHeaderFooterAdapter1);
mHeaderFooterAdapter3 = new DemoHeaderFooterAdapter(mHeaderFooterAdapter2);

mRecyclerView.setAdapter(mHeaderFooterAdapter3);

...

// using scrollToGroup()
AdapterPath path = new AdapterPath();

path.append(new AdapterPathSegment(mRecyclerView.getAdapter(), null));
path.append(mHeaderFooterAdapter3.getWrappedAdapterSegment());
path.append(mHeaderFooterAdapter2.getWrappedAdapterSegment());
path.append(mHeaderFooterAdapter1.getWrappedAdapterSegment());

mRecyclerViewExpandableItemManager.scrollToGroup(
    groupPosition, childItemHeight, topMargin, bottomMargin, path);
```


Also, please use the latest develop branch library via JitPack to use the new `scrollToGroup()` method;

```gradle
repositories {
    maven { url "https://jitpack.io" }
}
dependencies {
    compile 'com.github.h6ah4i:android-advancedrecyclerview:e7ae14d6ea47474fd45985df6ede21eccdcf256d'
}
```

**Comment by LoveqLRC** [comment]
Thank you very much for your answer.  I will try it later
