### ISSUE TITLE
How to disable SWAP & MOVE both and handle custom drop at end dragging.

### ISSUE THREAD

**Issue by nishyadav** [h6ah4i/android-advancedrecyclerview#391]
I need to disable SWAP & MOVE both while user is dragging image. And need to display shadow/alpha on allowed drop position.
And when finally drag ends, I need to manually reposition items.

I tried always returning false from onCheckCanDrop. But in that case fromPosition & toPosition are returned same in onItemDragFinished.

**Comment by h6ah4i** [comment]
Hi. Unfortunately, this library does not support such operation for now. I suppose [`ItemTouchHelper`](https://developer.android.com/reference/android/support/v7/widget/helper/ItemTouchHelper.Callback.html) can handle the requirements what you need, but sorry I am not familiar with the helper class 😞
