### ISSUE TITLE
SwipeManager

### ISSUE THREAD

**Issue by jpshelley** [h6ah4i/android-advancedrecyclerview#4]
I believe the SwipeManager when calling attach here:
https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager.java#L138

Then going here:
https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/utils/WrapperAdapterUtils.java#L27

Should check if:
```
adapter.getClass().isInstance(class)
```

at least thats how I got my code to work with it. I don't see how the super class could be an instance of the subclass adapter? It would have to be the opposite right?

**Comment by h6ah4i** [comment]
I’m afraid that you are trying to attach **non wrapped adapter** instance to SwipeManager.

The initialization order should be:

```java
RecyclerView rv = (RecyclerView) findViewById(R.id.foo);

RecyclerViewSwipeManager swipeManager = new RecyclerViewSwipeManager();

MyAdapter myAdapter = new MyAdapter();
RecyclerView.Adapter wrappedAdapter = swipeManager.createWrappedAdapter(myAdapter);

// !!! requires the wrappedAdapter instence, not myAdapter. !!!
rv.setAdapter(wrappedAdapter);

swipeManager.attachRecyclerView(rv);

...

class MyAdapter implements SwipeableItemAdapter<MyAdapter.ViewHolder> 
{
    public static class ViewHolder extends AbstractSwipeableItemViewHolder {
    }
}
```

**Comment by jpshelley** [comment]
@h6ah4i I'll give it another shot although I thought I did that. After attempting to implement it the first time, it seems really confusing, and the fact that there is a linear dependency for the swipeManager isn't the best idea. If you have ideas on making it simpler/easier to use I'd be happy to help. (I'll comment back here once I get it working.)

**Comment by jpshelley** [comment]
You're right simple mistake. (Although making the library easier more modular might help with that issue!)
