### ISSUE TITLE
Public callback for onSwipeItemStarted()

### ISSUE THREAD

**Issue by zacharee** [h6ah4i/android-advancedrecyclerview#400]
I noticed there's a lot in this library that lets you set reactions, etc, based on when a swipe has completed, but there doesn't seem to be any way to perform an action when a swipe is started. I noticed this in `SwipeableItemWrapperAdapter`:

    // NOTE: This method is called from RecyclerViewSwipeManager
    /*package*/ void onSwipeItemStarted(RecyclerViewSwipeManager manager, RecyclerView.ViewHolder holder, long id) {
        if (LOCAL_LOGD) {
            Log.d(TAG, "onSwipeItemStarted(holder = " + holder + ", id = " + id + ")");
        }

        mSwipingItemId = id;

        notifyDataSetChanged();
    }

Below that is `onSwipeItemFinished()`, which calls the interface method `onSwipeItem()`. Is it possible to have `onSwipeItemStarted()` to call its own interface method, so we can use it too?

**Comment by h6ah4i** [comment]
Hi. Thanks for the good suggestion! I will add a new call back method to `SwipeableItemAdapter`. 

I think this change can also solve an another problem. I am going to move the `notifyDataSetChanged()` method call into the new callback, so users can gain fine controls how to invalidate itemViews. (related: #395, #232, #129)

**Comment by zacharee** [comment]
I look forward to it!

_Sent from my LGE LG-H918 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by h6ah4i** [comment]
Released in v0.11.0.
