### ISSUE TITLE
The animation did not run when set GridLayoutManager

### ISSUE THREAD

**Issue by csshuai** [h6ah4i/android-advancedrecyclerview#402]
The animation did not run when set GridLayoutManager

[Look at this video](https://github.com/csshuai/android-advancedrecyclerview/blob/master/device-2017-07-14-113707.mp4)

**Comment by h6ah4i** [comment]
@csshuai Hi. Sorry for the late response 🙇 

Unfortunately, I can't fix the behavior because its designed behavior by RecyclerView. Please check the following issue for more details.

- Snapping on first item with draggable grid #389

Regards.
