### ISSUE TITLE
Draggable Swipeable RecyclerView is swipeable, but not draggable

### ISSUE THREAD

**Issue by theduffmaster** [h6ah4i/android-advancedrecyclerview#403]
Sorry to bother you, but I've spent a while trying to fix this and I can't seem to find a solution. I have a RecyclerView which I am trying to make both swipeable and draggable. I implemented what I found in your example, and now my RecyclerView is swipeable but not draggable. I have tried setting onCheckCanStartDrag to true, but that didn't do anything so I doubt it's that. I have tried playing around with the initiation order, with enabling and disabling different things. However, if I remove all the swiping parts it does drag successfully. Also, my ViewHolder extends AbstractDraggableSwipeableItemViewHolder. Is this normal? Am I doing something wrong?

Here are the relevant files:
[Adapter](https://github.com/theduffmaster/Phonograph/blob/dynamic_playing_queue/app/src/main/java/com/kabouzeid/gramophone/adapter/song/PlayingQueueAdapter.java)

[Fragment](https://github.com/theduffmaster/Phonograph/blob/dynamic_playing_queue/app/src/main/java/com/kabouzeid/gramophone/ui/fragments/player/card/CardPlayerFragment.java)

[RecyclerView Item's Layout](https://github.com/theduffmaster/Phonograph/blob/dynamic_playing_queue/app/src/main/res/layout/item_list.xml)

[Fragment's Layout](https://github.com/theduffmaster/Phonograph/blob/dynamic_playing_queue/app/src/main/res/layout/fragment_card_player.xml)

**Comment by h6ah4i** [comment]
@theduffmaster Hi. Sorry for the very late response 🙇 

I noticed that there is a mistake during the initialization process;

```java
wrappedAdapter = recyclerViewDragDropManager.createWrappedAdapter(playingQueueAdapter);
wrappedAdapter = recyclerViewSwipeManager.createWrappedAdapter(playingQueueAdapter);
```

SHOULD BE:
```java

```java
wrappedAdapter = recyclerViewDragDropManager.createWrappedAdapter(playingQueueAdapter);
wrappedAdapter = recyclerViewSwipeManager.createWrappedAdapter(wrappedAdapter);
```

**Comment by theduffmaster** [comment]
IT WORKS! Thank you for the help, much appreciated!
