### ISSUE TITLE
Swipe not working if RecyclerView is using a GridLayout

### ISSUE THREAD

**Issue by kdomingo** [h6ah4i/android-advancedrecyclerview#41]
Is there any way that we can implement it when the layout is a `GridLayout`?

**Comment by fedeamura** [comment]
+1, i really want use dragsort with GridLayout or StaggerredLayout

**Comment by h6ah4i** [comment]
Hi. I have just published v0.8.0 and it supports swiping with `GridLayoutManager` (and maybe `StaggerredLayoutManager` also).
