### ISSUE TITLE
how change color ExpandableItemIndicator 

### ISSUE THREAD

**Issue by miaaad** [h6ah4i/android-advancedrecyclerview#418]
i want change color ExpandableItemIndicator but not work  how change just color ExpandableItemIndicator not background ? 

this doesn't work 

holder.mIndicator.setBackgroundResource(R.color.text_color_price);
or
holder.mIndicator.setBackgroundColor(Color.parseColor("#2f2f2f"));

      if ((expandState & Expandable.STATE_FLAG_IS_EXPANDED) != 0) {
        bgResId = R.drawable.bg_group_item_expanded_state;
        holder.mTextView.setTextColor(Color.WHITE);
        holder.mIndicator.setBackgroundResource(R.color.textColor);
        isExpanded = true;
      } else {
        bgResId = R.drawable.bg_group_item_normal_state;
        holder.mTextView.setTextColor(Color.parseColor("#1d1d1d"));
        holder.mIndicator.setBackgroundColor(Color.parseColor("#2f2f2f"));
        isExpanded = false;
      }

i just change color like when change textcolor . Thank you

**Comment by h6ah4i** [comment]
Sorry for the late reply 🙇 

Use [`DrawableCompat.setTint()`](https://developer.android.com/reference/android/support/v4/graphics/drawable/DrawableCompat.html) to change indicator color. Also, the `ExpandableItemIndicator` class is just a sample code so you can modify it like the following.

```java
class ExpandableItemIndicatorImplAnim extends ExpandableItemIndicator.Impl {
    ...
    @Override
    public void setExpandedState(boolean isExpanded, boolean animate) {
        if (animate) {
            @DrawableRes int resId = isExpanded ? R.drawable.ic_expand_more_to_expand_less : R.drawable.ic_expand_less_to_expand_more;
            mImageView.setImageResource(resId);
            ((Animatable) mImageView.getDrawable()).start();
        } else {
            @DrawableRes int resId = isExpanded ? R.drawable.ic_expand_less : R.drawable.ic_expand_more;
            mImageView.setImageResource(resId);
        }
        DrawableCompat.setTint(mImageView.getDrawable(), Color.RED);  <-- ADD THIS LINE
    }
}
```
