### ISSUE TITLE
How to change the advanced receyclerview to horizontal layout with drag & drop working?

### ISSUE THREAD

**Issue by werther-luo** [h6ah4i/android-advancedrecyclerview#42]

**Comment by jdourlens** [comment]
Does anyone has a clue?

**Comment by vinayak-garg** [comment]
I managed to do just that. It is quite simple. Just replace `getY` with `getX`, `translationY` with `translationX`, `getHeight` with `getWidth` etc. You can look at this particular branch in my fork - https://github.com/vinayak-garg/android-advancedrecyclerview/tree/customize. I have customised it only for 'drag on long press' example.

**Comment by werther-luo** [comment]
@vinayak-garg thanks, it worked, helped a lot

**Comment by h6ah4i** [comment]
The v0.8.0 is supporting horizontal layout.
