### ISSUE TITLE
How to grouping drag & drop..

### ISSUE THREAD

**Issue by MiniMing-Lee** [h6ah4i/android-advancedrecyclerview#43]
I have section list...

SECTION 1
  item 1
  item 2
  item 3
SECTION 2
  item 4
  item 5
  item 6

-----------------------------------------------------------------------------

I want SECTION is that do not move...
Is it possible?

SECTION 1
  item 1
  item 2
  **item 4**
SECTION 2
  **item 3**
  item 5
  item 6

### Thank-you for great lib.

**Comment by h6ah4i** [comment]
Unfortunately this library does not support such behavior :disappointed:
