### ISSUE TITLE
Click effect on GroupView

### ISSUE THREAD

**Issue by marbat87** [h6ah4i/android-advancedrecyclerview#44]
Hi,

I noticed that when user clicks on a group in order to expand or collapse it, the "click effect" (for example ripple effect) is catched by something and it is not shown.
Instead, while keeping the item pressed, the ripple effect is shown.
This happens both in your example and in my application.

If I change "onCheckCanExpandOrCollapseGroup" in order  to return FALSE, the click effect is shown, but obviously the item is not expanded/collapsed.

Is there a way to fix it?

Thanks in advance

**Comment by h6ah4i** [comment]
Hi. Thanks for your report. 

Workaround:

Make `onCheckCanExpandOrCollapseGroup` returns `false` and set `View.onClickLIstener` for each group views. Then you can use these two methods to expand/collapse the group.

- `RecyclerViewExpandableItemManager.expandGroup(int groupPosition)`
- `RecyclerViewExpandableItemManager.collapseGroup(int groupPosition)`

see also.) Force expand/colapse #11

**Comment by marbat87** [comment]
Hi,

Thanks for the answer.

I had found that workaround yet.
But unfortunately, using that workaround, when user clicks on the morphing arrow nothing happens, because it has not an "onclick" event and I think it is a bit bothering for user.
Groups expand/collapse only clicking on the group title...

Thanks in advance.

**Comment by h6ah4i** [comment]
Found a workaround.

```java
```

**Comment by marbat87** [comment]
Do you mean in the standard implementation or in the one with the workaround?

**Comment by h6ah4i** [comment]
Just a workaround for now. Because it seems like a bug of MorphButton class. MorphButton consumes touch event even if `android:enable="false"` and/or `android:clickable="false"` specified in xml.

**Comment by Kuci** [comment]
Why do you intercept touch here: [RecyclerViewExpandableItemManager.java#L242-L244](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/RecyclerViewExpandableItemManager.java#L242-L244) I think you should not do that and I think it's root of the problem.

**Comment by h6ah4i** [comment]
@Kuci Thanks for your advice! I'll fix this issue tomorrow.

**Comment by Kuci** [comment]
I confirm the bug is fixed in the latest version. Thank you.
