### ISSUE TITLE
How to swipe?

### ISSUE THREAD

**Issue by freezy** [h6ah4i/android-advancedrecyclerview#45]
It just doesn't swipe. It displays, scrolls and everything, but items just stay at the same place when trying to swipe them horizontally. Here's what I did:

- Wrapped my adapter using `RecyclerViewSwipeManager#createWrappedAdapter()`
- Attached my recycler using `RecyclerViewSwipeManager#attachRecyclerView()`
- Used `SwipeDismissItemAnimator` as animator
- Made my adapter implement `SwipeableItemAdapter`:
  - `onGetSwipeReactionType()` always returns `RecyclerViewSwipeManager.REACTION_CAN_SWIPE_BOTH`
  - `onSetSwipeBackground()` does nothing
  - `onSwipeItem()` always returns `RecyclerViewSwipeManager.AFTER_SWIPE_REACTION_DEFAULT`
  - `onPerformAfterSwipeReaction()` does nothing
- Made my view holder extend `AbstractSwipeableItemViewHolder`:
  - Content layout is wrapped into a `FrameLayout`
  - Content layout is returned in `getSwipeableContainerView()`
- Overrode `getItemId()`, returning a unique ID for each item

I also did the `RecyclerViewTouchActionGuardManager` thing from the example. 

What did I miss? 

My next step would by copying the whole example into my project and clean up line by line. This will take me hours. Any hints from anyone who went through this would be greatly appreciated.

**Comment by Liliniser** [comment]
```java
@Override
public int onGetSwipeReactionType(ViewHolder viewHolder, int position, int x, int y) {
    // What did you return here?
    return RecyclerViewSwipeManager.REACTION_CAN_SWIPE_BOTH;
}
```

**Comment by freezy** [comment]
Returning always `RecyclerViewSwipeManager.REACTION_CAN_SWIPE_BOTH`, like in your code above.

**Comment by egor-n** [comment]
Your adapter should have stable ids:

    setHasStableIds(true);

**Comment by freezy** [comment]
@Liliniser: That was the missing piece. Thanks a lot, you've saved the day! :)
