### ISSUE TITLE
Programmatically scroll

### ISSUE THREAD

**Issue by FetFrumos** [h6ah4i/android-advancedrecyclerview#470]
I use advancedrecyclerview. This is wonderful component. I have groups with children. I have a group that is at the very bottom of the screen. I click to expand - it happens, but the children are at the bottom. User must scroll. How to do it programmatically? I will be grateful for any ideas.

**Comment by 4sskick** [comment]
did you already got the solution?
I implement the expandable & drag feature of library. But i can't to make it scroll to the right position with 
`recyclerview.smoothScrollToPosition(selectedPos)` it scrolled but not in the right position. and sometimes not scrolled at all
