### ISSUE TITLE
Repeated animation problem

### ISSUE THREAD

**Issue by soapsign** [h6ah4i/android-advancedrecyclerview#5]
After Drag&Drop the dragged cell restores to original position and starts the translation animation again to its dropped position. How can I fix this? Thank a lot.

**Comment by h6ah4i** [comment]
Hi. Could you provide some example code to reproduce the issue?

**Comment by soapsign** [comment]
I found the problem, its about the getItemId not returning stable ID.
Does this library required stable id adapter to work?
Its not mentioned in any documentation.

**Comment by h6ah4i** [comment]
Yes, this library requires stable ID. If the getItemId() method is not implemented properly, will causes exceptions or will animates incorrectly. Sorry for the inconvenience, I'll improve the documentations as soon as possible :sweat:

**Comment by h6ah4i** [comment]
I've added the comments about static ID requirements in the v0.6.2 sample codes.
