### ISSUE TITLE
CPU usage 30-40% while Idle

### ISSUE THREAD

**Issue by slarin** [h6ah4i/android-advancedrecyclerview#50]
Great Library, but CPU usage 30-40% while Idle

**Comment by h6ah4i** [comment]
Can't reproduce. Could you upload sample code or something else? I will take a look later :)

**Comment by slarin** [comment]
I use Android Studio 1.3 Preview 3
Open CPU tab in Android Studio 
![cpu usage](https://cloud.githubusercontent.com/assets/11872389/8123389/fb4e76f2-10fa-11e5-9a1d-41fdaaf4895e.jpg)

**Comment by h6ah4i** [comment]
Thanks! I have just turned out which is the culprit. It will be fixed in the next release.
