### ISSUE TITLE
Unnecessary call of onCreateGroupViewHolder()

### ISSUE THREAD

**Issue by nemanja87ns** [h6ah4i/android-advancedrecyclerview#51]
Hi,

I noticed a problem of unnecessary calling of onCreateGroupViewHolder() method after group item is clicked. This represents badly because in onCheckCanExpandOrCollapseGroup() method I check the expand parameter based on which I set expand or collapse arrow image.

Expand arrow is set by default in the layout and this is a sequence which happens to me:
- I click on group item
- in the onCheckCanExpandOrCollapseGroup() i set the collapse image
- onCreateGroupViewHolder() is called setting the image to default value (expand)
- it results with expanded list and expand drawable which is inconsistent.

I didn't had this issue with 0.6.2 and recyclerview-v7:21.0.3. It happens on versions 0.7.1 and 22.2.0.

**Comment by h6ah4i** [comment]
Maybe the cause is the same as #35. Try  to add `setSupportsChangeAnimations(false)`.

**Comment by nemanja87ns** [comment]
Yes, after adding setSupportsChangeAnimations(false) I no longer have this issue.

Is this a temporary fix and do I have some limitations in the future because of it?

**Comment by h6ah4i** [comment]
I suppose it is not a temporary fix and it will also required in the feature. Calling setSupportsChangeAnimations(false) just enables legacy behavior same as until recyclerview-v21, and this library requires the legacy behavior for now.

The limitation is... you can't use *item change animations* at all!

**Comment by nemanja87ns** [comment]
Thanks!
