### ISSUE TITLE
Wrap_content does not work with recycler view.

### ISSUE THREAD

**Issue by MoizAli** [h6ah4i/android-advancedrecyclerview#53]
I have looked at length at this issue and its a general problem with the layoutmanager. But the linearlayout manager in this link at least wraps the content:
http://stackoverflow.com/a/28303955/1182140

But then it assumes that there are no child elements. Has anyone else faced this problem?

**Comment by h6ah4i** [comment]
That is a common RecyclerView problem. Mark this issue as closed.
