### ISSUE TITLE
How to add groups "expanded" right away?

### ISSUE THREAD

**Issue by falsevapor** [h6ah4i/android-advancedrecyclerview#57]
Default behavior is of course that groups are added collapsed to the view. How would I force it to add them "expanded" from the beginning? Tried to play with expanded flags with not results.
Please help.

**Comment by falsevapor** [comment]
Sorry for being such a noob. I understand there's expandGroup and collapseGroup methods but when to call those? Seems natural that the onBindGroupViewHolder would be a wrong place for that. Is there some other event/moment I can do that?

**Comment by h6ah4i** [comment]
After calling the `RecyclerViewExpandableItemManager.attachRecyclerView()` method would be the best place.

https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_e/RecyclerListViewFragment.java#L98

**Comment by falsevapor** [comment]
LOL, well that worked! Thank you!

**Comment by wakim** [comment]
@h6ah4i , In my situation, i'm adding N expanded groups, and N can be huge.

Calling "expandGroup" worked, but there is any way to add it collapsed without having to call "expandGroup" for every group, maybe any flag on ViewHolder or something like that? If not, can you give any tip to implement this in your library, maybe i can try and make a PR.

**Comment by h6ah4i** [comment]
@wakim I think the best solution for this issue is adding a new method like the following;

```java
RecyclerViewExpandableItemManager.notifyGroupRangeInserted(
        int groupPosition, int count, boolean expanded)
```

The third argument specifies the initial state whether the inserted group items are expanded or not.

This library already has the same named method which does not have the third argument. If you are going to make a pull request, take a look this method.

Thanks
