### ISSUE TITLE
Potential bug in SwipeableItemWrapperAdapter

### ISSUE THREAD

**Issue by ayltai** [h6ah4i/android-advancedrecyclerview#58]
First of all, thank you for making this great library! It is powerful and easy to use.

I spot something strange in the code. In `SwipeableItemWrapperAdapter.onBindViewHolder()`, both lines 98 and 116 check for `holder instanceof SwipeableItemViewHolder` and assign `prevSwipeItemSlideAmount` and `swipeItemSlideAmount` to the same value `getSwipeItemSlideAmount()`, and then check for `prevSwipeItemSlideAmount != swipeItemSlideAmount`. Something wrong with `prevSwipeItemSlideAmount` value. A potential bug?

**Comment by h6ah4i** [comment]
Hi @ayltai. That is not a bug. The `SwipeableItemViewHolder.setSwipeItemSlideAmount()` function may be invoked during the `super.onBindViewHolder()` function*, so `prevSwipeItemSlideAmount` and `swipeItemSlideAmount` could be different.

*for instance:
- https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_s/MySwipeableItemAdapter.java#L151

**Comment by ayltai** [comment]
True. Thank you for the clarification.
