### ISSUE TITLE
Having a problem with dragging between sections.

### ISSUE THREAD

**Issue by kuffs** [h6ah4i/android-advancedrecyclerview#59]
I wish the user to be able to drag between sections but I am unable to get it to work how I expect.

I have amended the example code to reproduce my issue:

https://github.com/kuffs/android-advancedrecyclerview/commit/bc0119419229a22ec07dcb06b938504326cb8a02

Rather than throw an exception if the user drags to a section, I am attempting to just cancel the drop operation. However, the item being dropped completely disappears instead of returning to its original location.

Am I doing something incorrectly?

Thank you.

**Comment by Blankarsch** [comment]
I think it's not possible yet. But dragging Items between sections really would be great!

**Comment by h6ah4i** [comment]
@Blankarsch HI. I think it's possible to implement it with the current version. The `onCheckCanDrop()` method can be used for the purpose. I will create a demo project on this weekend. Thanks ;)

**Comment by h6ah4i** [comment]
@Blankarsch I have just updated the demo app. Please check the following commit. Thanks.

94b117e75f7dd79809c9f98eaeb1a296c1bc25cf
