### ISSUE TITLE
"settle back into place" animation on drag end

### ISSUE THREAD

**Issue by jonathanewerner** [h6ah4i/android-advancedrecyclerview#6]
it would be nice to have a animation of the dragged element back into it's old place or into its new place on drag end. (they way it happens in the Play Music app right now). do you plan on implementing this feature?
thanks for the great library!

**Comment by h6ah4i** [comment]
Thank you for your suggestion. I'll give it a try :)

**Comment by h6ah4i** [comment]
Implemented in 0.6.1.
