### ISSUE TITLE
After swipe/remove of a group crash in some cases 

### ISSUE THREAD

**Issue by falsevapor** [h6ah4i/android-advancedrecyclerview#64]
Hi. Trying to debug an issue where in some configurations the app crashes when a group item removed after swipe. In most cases it seems to work fine but in certain sets of data it seems to crash every time. It's very frustrating. It doesn't seem to happen with the sample.
I understand that the lib needs stable IDs. I have those.
In debugger I see that during onPerformAfterSwipeGroupReaction of MyAdapter notifyItemRemoved(flatPosition) is called. Stepping though that eventually end up in [ExpandablePositionTranslator.removeGroupItem](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/ExpandablePositionTranslator.java#L432).
Here it seems it's intentional that the cached items IDs and position info arrays are not adjusted and values are just copied to the removed item.
But what happens soon after (once we come out of the swipe/remove) is that my adapter gets calls such as getGroupItemViewType and getGroupID etc. for a group that's not there anymore.
Let's say I had 2 groups. I removed 1st group. After removal I get asked about both groups!
But I only have 1 group left. It's as if the lib forgot/doesn't know that the group was removed. 

Scenario that fails for me reliably:
2 groups
group 2 expanded
swipe away group 1
crash.
Again, this happens only with my data.
The example seems to work stably. Which makes me very sad in that I can't probably be helped. Hoping that you might have at least some idea about why ExpandablePositionTranslator might get confused.

**Comment by falsevapor** [comment]
More info.
I was able:
1. to simplify scenario an identify better
2. reproduce in the original sample application: demo_eds 

So. Easiest way to reproduce: 2 groups, first group collapsed (or has no children), second group expanded (!), swipe away the first group -> app ends.

More general identification/definition of the problem (!):
If last group is expanded when swiping away any previous collapsed (!) group results in crash.

All I had to do to make it easier to reproduce in the original example is shorten the sample data in 
[ExampleExpandableDataProvider](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/common/data/ExampleExpandableDataProvider.java#L42) from "ABCDEFGHIJKLMNOPQRSTUVWXYZ" to "AB" just to make two groups.
When in demo_eds:
1. expand second group ("B")
2. swipe away first group ("A")

**Comment by falsevapor** [comment]
And lastly the "Advanced RecyclerView Examples" unchanged app installed directly from play store also experiences the problem:
1. start the app
2. open "Expandable + Draggable + Swipeable"
3. scroll to the last group ("Z")
4. tap to expand
5. swipe away any previous group (such as "Y" or "X" etc..) that is currently visible (!) (don't scroll up!)
6. app quits

**Comment by indiandragon** [comment]
I agree with @falsevapor , this is serious show stopper for the applications using this excellent library.

If the last group is open and any other group above it which is in the view is swiped then the app will crash throwing a 'Index out of bound Exception'  at getPosition.

I tried to keep only one group open at a time by collapsing the other on touch, but unable to do so within the SwipeableItemWrapperAdapter as the instance of ExpandableRecyclerViewWrapperAdapter becomes null inside OnItemTouchListener.

**Comment by indiandragon** [comment]
Temporary fix I've chosen is to have a dummy final group item without any child . This does affect the user experience though.

**Comment by falsevapor** [comment]
My current workaround seems to be working. I don't notice any visual effect. But it is surely very ugly from code stand point.
So what I do is on swipe reaction I collapse the last group before removing the item and notifying about the removal and the right after notifying I expand it again.:
In the adapter:

    @Override
    public void onPerformAfterSwipeGroupReaction(MyGroupViewHolder holder, int groupPosition, int result, int reaction) {

        final AbstractExpandableDataProvider.GroupData item = mProvider.getGroupItem(groupPosition);
        final long expandablePosition = RecyclerViewExpandableItemManager.getPackedPositionForGroup(groupPosition);
        final int flatPosition = mExpandableItemManager.getFlatPosition(expandablePosition);

        if (reaction == RecyclerViewSwipeManager.AFTER_SWIPE_REACTION_REMOVE_ITEM) {

            ///////////////////////////
            //falsevapor: workaround for h6ah4i lib issue when crashes if last group expanded
            //collapse last group:
            int ngroups = getGroupCount();
            if (0 < ngroups)
                mExpandableItemManager.collapseGroup(ngroups - 1);
            //falsevapor: workaround for h6ah4i lib issue when crashes if last group expanded
            ///////////////////////////

            //actual removal
            mProvider.removeGroupItem(groupPosition);

            //notification of removal
            notifyItemRemoved(flatPosition);

            ///////////////////////////
            //falsevapor: workaround for h6ah4i lib issue when crashes if last group expanded
            //expand back
            ngroups = getGroupCount();
            if (0 < ngroups)
                mExpandableItemManager.expandGroup(ngroups - 1);
            //falsevapor: workaround for h6ah4i lib issue when crashes if last group expanded
            ///////////////////////////
            .....
       } else if (reaction == RecyclerViewSwipeManager.AFTER_SWIPE_REACTION_MOVE_TO_SWIPED_DIRECTION) {

            .....

        } else {
            .....
        }
    }

Seems to work and not flicker or jump around since actual update of the screen doesn't happen because we are doing it all in one call (?).
NOTE! I always expand the last group in my example. Because I have a requirement that groups are expanded all the time (weird I know). So proper workaround would be to check previous state of the last group before collapsing and then expanding if it was previously expanded.

**Comment by h6ah4i** [comment]
Sorry for the very late response :disappointed: 

Thank you for giving me the detail of scenario to procedure the bug! It helped me a lot and I have just fixed it now. I will release it as v0.7.3 tomorrow.

**Comment by indiandragon** [comment]
Thanks @h6ah4i  , eagerly awaiting the v0.7.3 build.  @falsevapor thanks for sharing your fix. I actually have two draggable-expandable-swipeable ARV's so I have just added a dummy group item with no child as a button to open the second ARV as a stop gap measure.

**Comment by h6ah4i** [comment]
@indiandragon I have just released a new version, but sorry for the delay of releasing v0.7.3, I was so busy last week...

**Comment by indiandragon** [comment]
@h6ah4i Thanks man ! I will check out new build, meanwhile I have added your patch and it did resolve the bug in question.

P.S Thanks for the impressive library and for maintaining it actively, much appreciated.

**Comment by falsevapor** [comment]
Looks like 0.7.3 fixed the issue! Thanks a lot!
