### ISSUE TITLE
Is there any way to detect drag start and drag end

### ISSUE THREAD

**Issue by leapfrog-santosh** [h6ah4i/android-advancedrecyclerview#65]
First of all awesome library, great great work. I am using `RecylerView` with `SwipeRefreshLayout`.So when drag is initiated, I need to disable `SwipeRefreshLayout` and when drag is stopped I need to enable `SwipeRefreshLayout`. Right now the only option I have is to add listeners inside `RecyclerViewDragDropManager`. Apart from that is there any built in function to access that.
Thanks

**Comment by tikimcfee** [comment]
Hey there!

Just wanted to add to this if possible. We could also greatly use a 'swipeDidStart()' and 'swipeDidFinish()' set of callbacks as well - some sort of Listener interface. 

As it stands, the callback flow of swipe interactions and when you'll actually get this is extremely complicate and hard to integrate with long press / tap events that are internal to the library. This would greatly help in, for example, turning on and off recycler viewholder binding, to avoid images reloading and resource reuse.

Thanks very much!

**Comment by h6ah4i** [comment]
@leapfrog-santosh @tikimcfee  Hi. I have just updated the library to v0.7.3 and added these new interfaces and methods. 

- RecyclerViewSwipeManager
  - [`OnItemSwipeEventListener `](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager.java#L223)
  - [`OnItemSwipeEventListener getOnItemSwipeEventListener()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager.java#L767)
  - [`void setOnItemSwipeEventListener(OnItemSwipeEventListener listener)`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager.java#L776)

- RecyclerViewDragDropManager
  - [`OnItemDragEventListener `](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/draggable/RecyclerViewDragDropManager.java#L89)
  - [`OnItemDragEventListener `](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/draggable/RecyclerViewDragDropManager.java#L89)
  - [`OnItemDragEventListener `](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/draggable/RecyclerViewDragDropManager.java#L89)
  - [`OnItemDragEventListener getOnItemDragEventListener()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/draggable/RecyclerViewDragDropManager.java#L417)
  - [`void setOnItemDragEventListener(OnItemDragEventListener listener)`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/draggable/RecyclerViewDragDropManager.java#L426)
