### ISSUE TITLE
Upgrade to com.android.support:recyclerview-v7:22.2.0

### ISSUE THREAD

**Issue by soapsign** [h6ah4i/android-advancedrecyclerview#66]
The 22.2 library introduced an abstract OnRequestDisallowInterceptTouchEvent() on RecyclerView.OnItemTouchListener that crashing the app as https://github.com/h6ah4i/android-advancedrecyclerview/search?utf8=%E2%9C%93&q=OnItemTouchListener these OnItemTouchListener has not override the new method.

**Comment by h6ah4i** [comment]
Thanks for the report. This issue has been solved in v0.7.2 (latest version), but I forgot to update the instruction written in the README page;

```gradle
dependencies {
    compile 'com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.7.2'
}
```
