### ISSUE TITLE
GridLayoutManager support

### ISSUE THREAD

**Issue by hzsweers** [h6ah4i/android-advancedrecyclerview#67]
Currently drag and drop only supports linear layout manager in the sense that it can only drag up and down.

**Comment by vinayak-garg** [comment]
It would be great to have a GridLayout support for this awesome library. Is it going to be supported anytime soon? And meanwhile is anyone aware of a working library which supports drag and drop with grid layout?
Also any thoughts on implementing GridLayout support for advanced-recyclerview? (Drag and drop only)

**Comment by h6ah4i** [comment]
Hi. I have just published v0.8.0. It supports GridLayoutManager and [a new demo](https://github.com/h6ah4i/android-advancedrecyclerview/tree/023f6c0cbcecc9f48f38622a7e8937b10b3d858c/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_d_grid) is added. Check it out!

![image](https://cloud.githubusercontent.com/assets/2552365/10262062/44bfbe8a-69f3-11e5-9aae-d9c0b32452fc.png)
