### ISSUE TITLE
Issues with stable ids

### ISSUE THREAD

**Issue by jpshelley** [h6ah4i/android-advancedrecyclerview#7]
Such as when the source is a dynamic amount of information. (Potentially 10-50 items depending on the data passed)

**Comment by h6ah4i** [comment]
Hi. This library requires stable IDs (`setHasStableIds(true)`) to the distinguish dragged/swiped target item. I think it's not an critical issue, because it's possible to assign non-overlapped identifiable number for each item of dynamic data source.
