### ISSUE TITLE
Error In -->Expandable(Add/Remove Items)

### ISSUE THREAD

**Issue by akash1223** [h6ah4i/android-advancedrecyclerview#75]
Error occur when we go through following steps
1.add group
2.add child in that group
3.expand group
5.remove group 
.
.
Error(OutofboundIndex exception )

**Comment by h6ah4i** [comment]
Thanks for the report! I will fix this as soon as possible.

**Comment by h6ah4i** [comment]
Fixed in 0.7.4.

**Comment by akash1223** [comment]
Thanks sir
