### ISSUE TITLE
How to notifyDataSetChanged when delete a group?

### ISSUE THREAD

**Issue by wliu6v** [h6ah4i/android-advancedrecyclerview#76]
Hi, @h6ah4i 

I'm trying to remove a group in a ExpandableDraggableItemAdapter. But after remove, the items belows the removed item won't refresh.

Here's my code 

	public Object removeItem(int groupPos) {
		mExpandManager.notifyGroupItemRemoved(groupPos);
		Object obj = mDataList.remove(groupPos);
		return obj;
	}

----

And there's another implementation. I try to refresh all the item below the deleted item.

Obviously, The code is ugly. And I want to know how to make it better.

	public Object removeItem2(int groupPos) {
		long packedPos = RecyclerViewExpandableItemManager
				.getPackedPositionForGroup(groupPos);
		int realPos = mExpandManager.getFlatPosition(packedPos);

		notifyItemRemoved(realPos);
		notifyItemRangeChanged(realPos, 999);  // 999 because I don't know how to getItemCount();

		Object obj = mDataList.remove(groupPos);
		return obj;
	}

**Comment by fabiendem** [comment]
Hi,
Try notifying after the remove call:

```
public Object removeItem(int groupPos) {
    Object obj = mDataList.remove(groupPos);
    mExpandManager.notifyGroupItemRemoved(groupPos);
    return obj;
}
```

**Comment by wliu6v** [comment]
@fabiendem 
Sorry for reply so late. Thanks for your solution and I have tried it, but it seems not working.

The problem like this:

Before remove (4 items in list):

  Item A - 0
  Item B - 1
  Item C - 2
  Item D - 3

--

After remove item B (3 items in list. the animation is normal, but the index doesn't refresh):

  Item A - 0
  Item C - 2
  Item D - crash

**Comment by fabiendem** [comment]
You need to make sure the getItemCount method returns a valid value. should be equal to: `mDataList.size()`

**Comment by wliu6v** [comment]
I'm using `ExpandableDraggableItemAdapte`r so I use `getGroupCount()` instead of `getItemCount()`, and it's still not working. Here's some more code:
	
    public TheAdapter(Activity activity, ArrayList dataList) {
        mActivity = activity;
        mDataList = dataList;
        setHasStableIds(true);
    }

    @Override
    public int getGroupCount() {
        return mDataList.size();
    }
    
    @Override
    public long getGroupId(int groupPosition) {
        return mDataList.get(groupPosition).getId() * 10000;
    }
    
    @Override
    public int getGroupItemViewType(int groupPosition) {
        return groupPosition == 0 ? 1 : 0; // first item should be larger.
    }

    public Object removeItem(int groupPos) {
        Object obj = mDataList.remove(groupPos);
        mExpandManager.notifyGroupItemRemoved(groupPos);
        return obj;
    }

**Comment by fabiendem** [comment]
Sorry can't see anything wrong.
Can you grab the exception stack trace and error message via logcat when the error occurs?

**Comment by wliu6v** [comment]
Index Exception.

After remove:

Item A - 0
Item C - 2
Item D - crash  [This index is 3, But after remove, there's only 3 items, not 4. So here occurs exception. ]

----

Crash Log:

	W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41b2fce0)
	W/System.err﹕ java.lang.IndexOutOfBoundsException: Invalid index 18, size is 18
	W/System.err﹕ at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	W/System.err﹕ at java.util.ArrayList.get(ArrayList.java:308)
	W/System.err﹕ at com.bar.foo.TheAdapter.getItem(TheAdapter.java:329)
	W/System.err﹕ at com.bar.foo.TheFragment$3.onMoreBtnClick(TheFragment.java:177)
	W/System.err﹕ at com.bar.foo.TheAdapter$2.onClick(TheAdapter.java:183)
	W/System.err﹕ at android.view.View.performClick(View.java:4445)
	W/System.err﹕ at android.view.View$PerformClick.run(View.java:18446)
	W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:733)
	W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
	W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
	W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5146)
	W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
	W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
	W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
	W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)

**Comment by wliu6v** [comment]
I can't provide the original code, so I write a demo for this issue, Here's the link:

https://github.com/wliu6v/RecyclerDemo/blob/master/app/src/main/java/demo/liuwei/recyclerexpanddemo/TheAdapter.java

In this file, the `removeItem()` method will crash after remove a item and click the last item. but the `removeItem2()` will be ok.

**Comment by h6ah4i** [comment]
@wliu6v Thanks, I'll take a look your demo code.

**Comment by h6ah4i** [comment]
You cannot reuse the `groupPosition` in callback. Position will be changed.
```java
	public void removeItem3(View v, int groupPos) {
		RecyclerView.ViewHolder vh = RecyclerViewAdapterUtils.getViewHolder(v);

		int flatPosition = vh.getAdapterPosition();
		long expandablePosition = mExpandableManager.getExpandablePosition(flatPosition);
		int groupPos2 = RecyclerViewExpandableItemManager.getPackedPositionGroup(expandablePosition);

		if (groupPos != groupPos2) {
			String msg = "groupPos: " + groupPos + " / groupPos2: " + groupPos2;
			Toast.makeText(v.getContext().getApplicationContext(), msg, Toast.LENGTH_SHORT).show();
		}

		mData.remove(groupPos2);
		mExpandableManager.notifyGroupItemRemoved(groupPos2);
	}
```

**Comment by wliu6v** [comment]
@h6ah4i Thanks for your reply but it seems not work. I update my code. Now the `removeItem()` method is your code. But it has the same problem with my original code.

**Comment by h6ah4i** [comment]
@wliu6v Try the following code. My old implementations can cause a crash when you click the list items frequently.

```java
	public void removeItem3(View v, int groupPos) {
		RecyclerView.ViewHolder vh = RecyclerViewAdapterUtils.getViewHolder(v);

		int flatPosition = vh.getAdapterPosition();

		if (flatPosition == RecyclerView.NO_POSITION) {
			return;
		}

		long expandablePosition = mExpandableManager.getExpandablePosition(flatPosition);
		int groupPos2 = RecyclerViewExpandableItemManager.getPackedPositionGroup(expandablePosition);

		if (groupPos != groupPos2) {
			String msg = "groupPos: " + groupPos + " / groupPos2: " + groupPos2;
			Toast.makeText(v.getContext().getApplicationContext(), msg, Toast.LENGTH_SHORT).show();
		}

		mData.remove(groupPos2);
		mExpandableManager.notifyGroupItemRemoved(groupPos2);
	}
```

**Comment by wliu6v** [comment]
@h6ah4i Your new solution will prevent crash when click the last item. But when I click the items between the removed one and the last one, the position still not right.

You can see the images below:

1. The original state.
2. I remove the Item E.
3. I click on Item G. The Item G should be , but because the position not right, so the expanded item is H, not G.

![1](https://cloud.githubusercontent.com/assets/5987831/9461641/7a9b4152-4b42-11e5-804f-e2c8b386c6a7.png)
![2](https://cloud.githubusercontent.com/assets/5987831/9461639/7a9982ae-4b42-11e5-9bdb-32f6650bbd04.png)
![3](https://cloud.githubusercontent.com/assets/5987831/9461640/7a9adbea-4b42-11e5-86d8-2acae598985d.png)

**Comment by wliu6v** [comment]
The following code is my `onBindGroupViewHolder()` method. If the `groupPosition` in `onClick()` is wrong?

	@Override
	public void onBindGroupViewHolder(GroupViewHolder groupViewHolder,
			final int groupPosition, int viewType) {
		groupViewHolder.tv.setText(mData.get(groupPosition).first);

		groupViewHolder.tv.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {

				if (mExpandableManager.isGroupExpanded(groupPosition)) {
					mExpandableManager.collapseGroup(groupPosition);
				} else {
					mExpandableManager.expandGroup(groupPosition);
				}
			}
		});

		groupViewHolder.mRemover.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {
				removeItem3(groupPosition, v);
			}
		});

	}

**Comment by h6ah4i** [comment]
That is the same problem. Have to re-calculate the item position from the view instance.

Code snippet:
```java
RecyclerView.ViewHolder vh = RecyclerViewAdapterUtils.getViewHolder(v);
int flatPosition = vh.getAdapterPosition();
long expandablePosition = mExpandableManager.getExpandablePosition(flatPosition);
int groupPos = RecyclerViewExpandableItemManager.getPackedPositionGroup(expandablePosition);
int childPos = RecyclerViewExpandableItemManager.getPackedPositionChild(expandablePosition);
```

FYI: This is not an Advanced RecyclerView specific issue, but rather a common practice for touch event handling of RecyclerView.

**Comment by wliu6v** [comment]
Thank you for your patiently reply! I had already know where the problem is.

The `recyclerView` won't refresh all item's positions after remove a item, so what I should do is get the real position by the view.
