### ISSUE TITLE
[DOC] build.gradle config

### ISSUE THREAD

**Issue by FedericoOldrini** [h6ah4i/android-advancedrecyclerview#8]
In "Getting started" is missing the jcentral() repository
```
repositories {
    jcenter()
}

dependencies {
    compile 'com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.6.1'
}
```

**Comment by h6ah4i** [comment]
Hi. Thanks for your suggestion. I think we can omit the `repositories { jcenter() }` call in build.gradle of the individual modules, because the project top-level build.gradle file has already include the jCenter repository by default. What do you think about it?

```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by FedericoOldrini** [comment]
Are you sure? I have only mavenCentral in my top level build.gradle

**Comment by h6ah4i** [comment]
Yes. According to the following web site, it was changed since Android Studio version 0.8.0. I guess you are using old template based top level build.gradle.

> (Projects created with Android Studio since version 0.8.0 have all defaulted to jcenter instead of mavenCentral)

https://code.google.com/p/android/issues/detail?id=72061
