### ISSUE TITLE
How to implement a ClickItemListener on Children ?

### ISSUE THREAD

**Issue by ssaurel** [h6ah4i/android-advancedrecyclerview#80]
Hello,

Is there a simple way to implement a click item listener on children ?

Sylvain

**Comment by vinayak-garg** [comment]
I have done it in following manner-
In the `onCreateViewHolder` setup the on click listener. As shown below.

        @Override
        public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            final LayoutInflater inflater = LayoutInflater.from(parent.getContext());
            final View v = inflater.inflate(R.layout.myview, parent, false);
            ViewHolder vh = new ViewHolder(v);
            v.setOnClickListener(vh);
            return vh;
        }

And in the `ViewHolder` class simply override the function `void onClick(View v) { }`

And be sure to use long press for dragging.

HTH

**Comment by FreakMurderer** [comment]
Ok, and but how get child position in this OnClick ?

**Comment by vinayak-garg** [comment]
@FreakMurderer : Simply call `getLayoutPosition();` to get the child position inside the `void onClick(View v) { }`

**Comment by FreakMurderer** [comment]
`Simply call getLayoutPosition();` = this absolutely wrong. On this way you never get properly childposition...

**Comment by FreakMurderer** [comment]
Look at 
https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_e_add_remove/MyAddRemoveExpandableItemAdapter.java#L219

This right way , But, in my opinion,  is very expensive and hard way ... Need more simplicity this things ...

**Comment by vinayak-garg** [comment]
I should mention that I only use drag and drop feature of this library. And `getLayoutPosition()` works fine for that.

**Comment by FreakMurderer** [comment]
If you use expandable recyclerView - you cannot get child position by getLayoutPosition, you understand or not, man ? 
If you use NOT expandable recyclerView - you can get item (not child or not Group item) position by getLayoutPosition ....

Example 
group1
- children1
- children2
- children3
group2
- children1
- children2
- children3

When you will be use get LayoutPosition for group2->children2 , you get position - 6.
But right child position is - 1.

**Comment by vinayak-garg** [comment]
I said that I **only use drag and drop**. To make it even more clear **I do not use expandable recycler view** feature.

Your explanation may help someone though.
