### ISSUE TITLE
onSaveInstanceState problems

### ISSUE THREAD

**Issue by FreakMurderer** [h6ah4i/android-advancedrecyclerview#82]
Look 
https://github.com/h6ah4i/android-advancedrecyclerview/blob/7e0b4ef282547385dcbe9cbc48913404abafcbe6/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_e/RecyclerListViewFragment.java#L41

this code `final Parcelable eimSavedState = (savedInstanceState != null) ? savedInstanceState.getParcelable(SAVED_STATE_EXPANDABLE_ITEM_MANAGER) : null;
        mRecyclerViewExpandableItemManager = new RecyclerViewExpandableItemManager(eimSavedState);` is bad , because

http://stackoverflow.com/a/25068471

What happened , if fragment with ExpandableStorageAdapter  is used in Pager ?

**Comment by h6ah4i** [comment]
This is not a library's issue. I think it is a design fault of Android's Fragment...

I recommend you to create a custom `ViewGroup` which manages saved state of `RecyclerView` and `RecyclerViewExpandableItemManager`.

1. Create a `ViewGroup` which extends some stock `ViewGroup` class. (`FrameLayout` is recommended)
2. Override `dispatchSaveInstanceState()` and `dispatchRestoreInstanceState()` to disable the automatic child view state saving.
3. Override `onSaveInstanceState()` and `onRestoreInstanceState()`  and save/restore the state of child `RecyclerView` and `RecyclerViewExpandableItemManager`.

Please refer the following superb article for more details;
- [Saving Android View state correctly](http://trickyandroid.com/saving-android-view-state-correctly/)

**Comment by FreakMurderer** [comment]
Thank you, but what you said about this decision: http://stackoverflow.com/a/25068471
I, try, and that work for me 
```java
public StorageFragment() {
        setArguments(new Bundle());
    }
```
and

```java
public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
       final Parcelable eimSavedState = (getArguments() != null) ? getArguments().getParcelable(SAVED_STATE_EXPANDABLE_ITEM_MANAGER) : null;
.....
```

and
```java
@Override
    public void onPause() {
        super.onPause();
        // save current state to support screen rotation, etc...
        if (mRecyclerViewExpandableItemManager != null) {
            getArguments().putParcelable(
                    SAVED_STATE_EXPANDABLE_ITEM_MANAGER,
                    mRecyclerViewExpandableItemManager.getSavedState());
        }
    }
```

Or that ridiculous  ? : )

**Comment by h6ah4i** [comment]
I do not recommend using Fragment's arguments for saving instance state.

The [`StatedFragment`](https://github.com/nuuneoi/StatedFragment) library was using that pattern for saving Fragment's state, but now this library is deprecated. The reason of deprecation is described on the following article written by the author of the StatedFragment library.

- [The Real Best Practices to Save/Restore Activity's and Fragment's state. (StatedFragment is now deprecated)](http://inthecheesefactory.com/blog/fragment-state-saving-best-practices/en)
- [Probably be the best way (?) to save/restore Android Fragment’s state so far](http://inthecheesefactory.com/blog/best-approach-to-keep-android-fragment-state/en)
