### ISSUE TITLE
Unnecessary animation on drag

### ISSUE THREAD

**Issue by papcio28** [h6ah4i/android-advancedrecyclerview#83]
Hello !
I implemented drag&drop Recycler View as in your example and I have some annoying problem. When I swipe some item RecyclerView animates position changing. It looks like playing back my drag gesture. 

How to remove this effect ? I need from dropped element to stay where I left it, not animating again.

Here you have a link for YouTube video with described effect : https://youtu.be/V3eBLiAkwws

**Comment by h6ah4i** [comment]
This library requires stable ID to work properly. Please call `setHasStableIds(true)` and implement the  `getItemId()` method properly.

Related isaues:
#22, #7, #5

**Comment by papcio28** [comment]
OK, you were right. I had dummy getItemId implementation (I just returned item position). I also have another bug in my code. My code which were changing item index in List was wrong. Now everything work perfect.

Thank you.
