### ISSUE TITLE
Better way get child and group position in...

### ISSUE THREAD

**Issue by FreakMurderer** [h6ah4i/android-advancedrecyclerview#84]
... AbstractExpandableItemAdapter ?
Please, give OnClick listener  example if clicked on children...

**Comment by h6ah4i** [comment]
Please see the ["Expandable (Add/Remove items)"](https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.8.0/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_e_add_remove/MyAddRemoveExpandableItemAdapter.java#L232) demo.

Thanks.
