### ISSUE TITLE
Change expand group speed

### ISSUE THREAD

**Issue by FreakMurderer** [h6ah4i/android-advancedrecyclerview#87]
How change expand group speed or delete expand animation (etc speed) absolutely.

Etc, like ExpandableListView behavior ...

**Comment by h6ah4i** [comment]
Use `RecyclerView.ItemAnimator`'s methods.

- [`RecyclerView.ItemAnimator.setMoveDuration(long moveDuration)`](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ItemAnimator.html#setMoveDuration%28long%29)
- [`RecyclerView.ItemAnimator.setRemoveDuration(long removeDuration)`](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ItemAnimator.html#setRemoveDuration%28long%29)
- [`RecyclerView.ItemAnimator.setAddDuration(long addDuration)`](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ItemAnimator.html#setAddDuration%28long%29)
