### ISSUE TITLE
enhancement for admob

### ISSUE THREAD

**Issue by jjhesk** [h6ah4i/android-advancedrecyclerview#89]
is that possible to add admob integration recyclerview?

**Comment by h6ah4i** [comment]
I do not have any plan to add any special support for AdMob. Is that feature really helps for many other app developers? 


The [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) is good a way to handle such problem. Create a wrapper adapter which automatically insert ads moderately. You can refer the implementation of the [`BaseWrapperAdapter`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/utils/BaseWrapperAdapter.java) in my library, or extend the class and override each methods as you need.
