### ISSUE TITLE
feature: hook to determine if item can be moved

### ISSUE THREAD

**Issue by jonathanewerner** [h6ah4i/android-advancedrecyclerview#9]
i do not think this is possible right now, but it would be great to have. :) i have the use case of section headers. 
the list looks like:
SECTION A
list item 1 type a
list item 2 type a
list item 3 type a
SECTION B
list item 1 type b
list item 2 type b
list item 3 type b

i want only the list items of type a to be drag-sortable.
right now it is for example possible to drag list item 1 (type a) *above* 'SECTION A'.

**Comment by egor-n** [comment]
Just return `REACTION_CAN_NOT_SWIPE_BOTH` in `onGetSwipeReactionType` for your sections.

**Comment by jonathanewerner** [comment]
this works if i try to drag the caption item itself -- but it doesn't disallow a position exchange with another item if i start the dragging from that one.

**Comment by h6ah4i** [comment]
Hi. Thanks for your the report. Current version (0.6.1) does not support such feature, so I'll implement that in next version.

**Comment by h6ah4i** [comment]
@jonathanewerner I've finished to implement the configurable drag-sortable range feature and pushed to the [develop branch](https://github.com/h6ah4i/android-advancedrecyclerview/tree/develop).

Please refer to the newly added two examples, if you have any troubles, let me know ;)

**Comment by jonathanewerner** [comment]
this looks straightforward. :) basically just implement onGetItemDraggableRange and i'm done right? great work, and so fast again. where can i buy you a virtual beer? :)
looking forward integrating this in my [app](https://github.com/jonathanewerner/leadsheets). (which i just pushed to github the first time, btw. :)

**Comment by h6ah4i** [comment]
> basically just implement onGetItemDraggableRange and i'm done right?

Yes, that's all :beer:

P.S. I've just submit small PRs on your app.

**Comment by h6ah4i** [comment]
This feature has been included v0.6.2.

**Comment by jonathanewerner** [comment]
implementation took about 2 minutes. awesome.
